# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .account_update import AccountUpdate, AccountUpdate_SingleUseToken
    from .ach import Ach
    from .ach_bank_account import AchBankAccount
    from .ach_bank_account_sec_code import AchBankAccountSecCode
    from .ach_deposit import AchDeposit
    from .ach_deposit_fee import AchDepositFee
    from .ach_deposit_summary import AchDepositSummary
    from .ach_fees import AchFees
    from .ach_payload import AchPayload
    from .ach_payload_account_type import AchPayloadAccountType
    from .ach_payload_sec_code import AchPayloadSecCode
    from .ach_source import AchSource
    from .ach_source_with_account_type import AchSourceWithAccountType
    from .ach_source_with_account_type_account_type import AchSourceWithAccountTypeAccountType
    from .activity_record import ActivityRecord
    from .activity_record_type import ActivityRecordType
    from .address import Address
    from .address_type import AddressType
    from .address_type_type import AddressTypeType
    from .amount import Amount
    from .apple_pay_response_session import ApplePayResponseSession
    from .authorization import Authorization
    from .authorization_authorization_response import AuthorizationAuthorizationResponse
    from .authorization_summary import AuthorizationSummary
    from .automatic_batch_close import AutomaticBatchClose
    from .balance import Balance
    from .balance_response_code import BalanceResponseCode
    from .bank_account_verification_result import BankAccountVerificationResult
    from .bank_transfer_breakdown import BankTransferBreakdown
    from .bank_transfer_breakdown_base import BankTransferBreakdownBase
    from .bank_transfer_customer import BankTransferCustomer
    from .bank_transfer_customer_notification_language import BankTransferCustomerNotificationLanguage
    from .bank_transfer_payment import BankTransferPayment
    from .bank_transfer_payment_bank_account import (
        BankTransferPaymentBankAccount,
        BankTransferPaymentBankAccount_Ach,
        BankTransferPaymentBankAccount_Pad,
    )
    from .bank_transfer_payment_order import BankTransferPaymentOrder
    from .bank_transfer_payment_order_base import BankTransferPaymentOrderBase
    from .bank_transfer_payment_paginated_list import BankTransferPaymentPaginatedList
    from .bank_transfer_payment_request_order import BankTransferPaymentRequestOrder
    from .bank_transfer_refund import BankTransferRefund
    from .bank_transfer_refund_bank_account import (
        BankTransferRefundBankAccount,
        BankTransferRefundBankAccount_Ach,
        BankTransferRefundBankAccount_Pad,
    )
    from .bank_transfer_refund_order import BankTransferRefundOrder
    from .bank_transfer_refund_paginated_list import BankTransferRefundPaginatedList
    from .bank_transfer_request_breakdown import BankTransferRequestBreakdown
    from .bank_transfer_result import BankTransferResult
    from .bank_transfer_result_status import BankTransferResultStatus
    from .bank_transfer_result_type import BankTransferResultType
    from .bank_transfer_return_summary import BankTransferReturnSummary
    from .base_intent import BaseIntent
    from .base_intent_status import BaseIntentStatus
    from .base_us import BaseUs
    from .base_us_annual import BaseUsAnnual
    from .base_us_annual_fee import BaseUsAnnualFee
    from .base_us_annual_fee_bill_in_month import BaseUsAnnualFeeBillInMonth
    from .base_us_monthly import BaseUsMonthly
    from .base_us_platinum_security import (
        BaseUsPlatinumSecurity,
        BaseUsPlatinumSecurity_Annual,
        BaseUsPlatinumSecurity_Monthly,
    )
    from .batch import Batch
    from .batch_summary import BatchSummary
    from .breakdown import Breakdown
    from .breakdown_adjustment import BreakdownAdjustment
    from .breakdown_base import BreakdownBase
    from .breakdown_for_payment_instructions import BreakdownForPaymentInstructions
    from .breakdown_request import BreakdownRequest
    from .business import Business
    from .business_country_of_operation import BusinessCountryOfOperation
    from .business_organization_type import BusinessOrganizationType
    from .card import Card
    from .card_balance import CardBalance
    from .card_balance_benefit_category import CardBalanceBenefitCategory
    from .card_bin_payload import CardBinPayload
    from .card_entry_method import CardEntryMethod
    from .card_info import CardInfo
    from .card_payload import CardPayload
    from .card_payload_account_type import CardPayloadAccountType
    from .card_payload_card_details import (
        CardPayloadCardDetails,
        CardPayloadCardDetails_Icc,
        CardPayloadCardDetails_Keyed,
        CardPayloadCardDetails_Raw,
        CardPayloadCardDetails_Swiped,
    )
    from .card_source import CardSource
    from .card_summary import CardSummary
    from .card_summary_type import CardSummaryType
    from .card_verification_result import CardVerificationResult
    from .choice_rate import ChoiceRate
    from .common_funding import CommonFunding
    from .common_funding_funding_schedule import CommonFundingFundingSchedule
    from .common_funding_status import CommonFundingStatus
    from .communication_type import CommunicationType
    from .consumer_choice import ConsumerChoice
    from .consumer_choice_fees import ConsumerChoiceFees
    from .contact import Contact
    from .contact_method import (
        ContactMethod,
        ContactMethod_Email,
        ContactMethod_Fax,
        ContactMethod_Mobile,
        ContactMethod_Phone,
    )
    from .contact_method_email import ContactMethodEmail
    from .contact_method_fax import ContactMethodFax
    from .contact_method_mobile import ContactMethodMobile
    from .contact_method_phone import ContactMethodPhone
    from .contact_type import ContactType
    from .convenience_fee import ConvenienceFee
    from .create_funding import CreateFunding
    from .create_processing_account import CreateProcessingAccount
    from .create_processing_account_business_type import CreateProcessingAccountBusinessType
    from .credential_on_file import CredentialOnFile
    from .credential_on_file_mit_agreement import CredentialOnFileMitAgreement
    from .currency import Currency
    from .custom_field import CustomField
    from .custom_label import CustomLabel
    from .custom_label_element import CustomLabelElement
    from .customer import Customer
    from .customer_adjustment import CustomerAdjustment
    from .customer_notification_language import CustomerNotificationLanguage
    from .customization_options import CustomizationOptions
    from .customization_options_entry_method import CustomizationOptionsEntryMethod
    from .dcc_offer import DccOffer
    from .device import Device
    from .device_category import DeviceCategory
    from .device_config import DeviceConfig
    from .device_instruction import DeviceInstruction
    from .device_instruction_status import DeviceInstructionStatus
    from .device_model import DeviceModel
    from .digital_wallet_payload import DigitalWalletPayload
    from .digital_wallet_payload_account_type import DigitalWalletPayloadAccountType
    from .digital_wallet_payload_service_provider import DigitalWalletPayloadServiceProvider
    from .dispute import Dispute
    from .dispute_current_status import DisputeCurrentStatus
    from .dispute_dispute_type import DisputeDisputeType
    from .dispute_status import DisputeStatus
    from .dispute_status_status import DisputeStatusStatus
    from .dual_pricing import DualPricing
    from .dual_pricing_alternative_tender import DualPricingAlternativeTender
    from .dukpt_pin_details import DukptPinDetails
    from .ebt_details import EbtDetails
    from .ebt_details_benefit_category import EbtDetailsBenefitCategory
    from .ebt_details_with_voucher import EbtDetailsWithVoucher
    from .ebt_disabled import EbtDisabled
    from .ebt_enabled import EbtEnabled
    from .ebt_enabled_ebt_type import EbtEnabledEbtType
    from .electronic_benefits_transfer import ElectronicBenefitsTransfer
    from .emv_tag import EmvTag
    from .encrypted_swiped_data_format import EncryptedSwipedDataFormat
    from .encrypted_swiped_data_format_fallback_reason import EncryptedSwipedDataFormatFallbackReason
    from .encryption_capable_device import EncryptionCapableDevice
    from .enhanced_interchange import EnhancedInterchange
    from .event_subscription import EventSubscription
    from .event_subscription_status import EventSubscriptionStatus
    from .first_txn_reference_data import FirstTxnReferenceData
    from .five_hundred import FiveHundred
    from .five_hundred_errors_item import FiveHundredErrorsItem
    from .flat_rate import FlatRate
    from .flat_rate_amex_direct import FlatRateAmexDirect
    from .flat_rate_fees import FlatRateFees
    from .flat_rate_fees_amex import FlatRateFeesAmex, FlatRateFeesAmex_Direct
    from .four_hundred import FourHundred
    from .four_hundred_errors_item import FourHundredErrorsItem
    from .four_hundred_fifteen import FourHundredFifteen
    from .four_hundred_four import FourHundredFour
    from .four_hundred_nine import FourHundredNine
    from .four_hundred_nine_errors_item import FourHundredNineErrorsItem
    from .four_hundred_one import FourHundredOne
    from .four_hundred_six import FourHundredSix
    from .four_hundred_thirteen import FourHundredThirteen
    from .four_hundred_three import FourHundredThree
    from .fully_encrypted_keyed_data_format import FullyEncryptedKeyedDataFormat
    from .funding_account import FundingAccount
    from .funding_account_status import FundingAccountStatus
    from .funding_account_summary import FundingAccountSummary
    from .funding_account_summary_status import FundingAccountSummaryStatus
    from .funding_account_type import FundingAccountType
    from .funding_account_use import FundingAccountUse
    from .funding_recipient import FundingRecipient
    from .funding_recipient_funding_accounts_item import FundingRecipientFundingAccountsItem
    from .funding_recipient_funding_accounts_item_link import FundingRecipientFundingAccountsItemLink
    from .funding_recipient_funding_accounts_item_status import FundingRecipientFundingAccountsItemStatus
    from .funding_recipient_owners_item import FundingRecipientOwnersItem
    from .funding_recipient_owners_item_link import FundingRecipientOwnersItemLink
    from .funding_recipient_recipient_type import FundingRecipientRecipientType
    from .funding_recipient_status import FundingRecipientStatus
    from .fx_rate import FxRate
    from .fx_rate_inquiry_result import FxRateInquiryResult
    from .gateway_three_d_secure import GatewayThreeDSecure
    from .gateway_us import GatewayUs
    from .gateway_us_50 import GatewayUs50
    from .gateway_us_50_fees import GatewayUs50Fees
    from .gateway_us_fees import GatewayUsFees
    from .hardware_advantage_plan import HardwareAdvantagePlan
    from .host_configuration import HostConfiguration
    from .host_configuration_configuration import HostConfigurationConfiguration, HostConfigurationConfiguration_Tsys
    from .hosted_fields_create_session_response import HostedFieldsCreateSessionResponse
    from .icc_card_details import IccCardDetails
    from .icc_card_details_downgrade_to import IccCardDetailsDowngradeTo
    from .identifier import Identifier
    from .identifier_type import IdentifierType
    from .instruction import Instruction
    from .instruction_merchants_item import InstructionMerchantsItem
    from .instruction_merchants_item_link import InstructionMerchantsItemLink
    from .instruction_merchants_item_recipients_item import InstructionMerchantsItemRecipientsItem
    from .instruction_merchants_item_recipients_item_amount import InstructionMerchantsItemRecipientsItemAmount
    from .instruction_merchants_item_recipients_item_amount_currency import (
        InstructionMerchantsItemRecipientsItemAmountCurrency,
    )
    from .instruction_merchants_item_recipients_item_link import InstructionMerchantsItemRecipientsItemLink
    from .instruction_merchants_item_recipients_item_payment_method import (
        InstructionMerchantsItemRecipientsItemPaymentMethod,
    )
    from .instruction_merchants_item_recipients_item_status import InstructionMerchantsItemRecipientsItemStatus
    from .instruction_status import InstructionStatus
    from .interchange_plus import InterchangePlus
    from .interchange_plus_amex_direct import InterchangePlusAmexDirect
    from .interchange_plus_amex_opt_blue import InterchangePlusAmexOptBlue
    from .interchange_plus_fees import InterchangePlusFees
    from .interchange_plus_fees_amex import (
        InterchangePlusFeesAmex,
        InterchangePlusFeesAmex_Direct,
        InterchangePlusFeesAmex_OptBlue,
    )
    from .interchange_plus_plus import InterchangePlusPlus
    from .interchange_plus_plus_amex_direct import InterchangePlusPlusAmexDirect
    from .interchange_plus_plus_amex_opt_blue import InterchangePlusPlusAmexOptBlue
    from .interchange_plus_plus_fees import InterchangePlusPlusFees
    from .interchange_plus_plus_fees_amex import (
        InterchangePlusPlusFeesAmex,
        InterchangePlusPlusFeesAmex_Direct,
        InterchangePlusPlusFeesAmex_OptBlue,
    )
    from .interchange_plus_tiered_3 import InterchangePlusTiered3
    from .interchange_plus_tiered_3_amex_direct import InterchangePlusTiered3AmexDirect
    from .interchange_plus_tiered_3_amex_opt_blue import InterchangePlusTiered3AmexOptBlue
    from .interchange_plus_tiered_3_fees import InterchangePlusTiered3Fees
    from .interchange_plus_tiered_3_fees_amex import (
        InterchangePlusTiered3FeesAmex,
        InterchangePlusTiered3FeesAmex_Direct,
        InterchangePlusTiered3FeesAmex_OptBlue,
    )
    from .ip_address import IpAddress
    from .ip_address_type import IpAddressType
    from .itemized_breakdown import ItemizedBreakdown
    from .itemized_breakdown_request import ItemizedBreakdownRequest
    from .keyed_card_details import KeyedCardDetails
    from .keyed_card_details_keyed_data import (
        KeyedCardDetailsKeyedData,
        KeyedCardDetailsKeyedData_FullyEncrypted,
        KeyedCardDetailsKeyedData_PartiallyEncrypted,
        KeyedCardDetailsKeyedData_PlainText,
    )
    from .keyed_card_details_pin_details import KeyedCardDetailsPinDetails, KeyedCardDetailsPinDetails_Dukpt
    from .legal_address import LegalAddress
    from .line_item import LineItem
    from .line_item_base import LineItemBase
    from .line_item_request import LineItemRequest
    from .link import Link
    from .links import Links
    from .list_funding_accounts import ListFundingAccounts
    from .manual_batch_close import ManualBatchClose
    from .merchant_balance import MerchantBalance
    from .merchant_platform import MerchantPlatform
    from .merchant_platform_processing_accounts_item import MerchantPlatformProcessingAccountsItem
    from .merchant_platform_processing_accounts_item_link import MerchantPlatformProcessingAccountsItemLink
    from .merchant_platform_processing_accounts_item_status import MerchantPlatformProcessingAccountsItemStatus
    from .merchant_summary import MerchantSummary
    from .multi_use_payment_link import MultiUsePaymentLink
    from .multi_use_payment_link_auth_type import MultiUsePaymentLinkAuthType
    from .multi_use_payment_link_order import MultiUsePaymentLinkOrder
    from .multi_use_payment_link_order_charge import (
        MultiUsePaymentLinkOrderCharge,
        MultiUsePaymentLinkOrderCharge_Preset,
        MultiUsePaymentLinkOrderCharge_Prompt,
    )
    from .multi_use_payment_link_payment_methods_item import MultiUsePaymentLinkPaymentMethodsItem
    from .multi_use_payment_link_status import MultiUsePaymentLinkStatus
    from .notification import Notification, Notification_Webhook
    from .offline_processing import OfflineProcessing
    from .offline_processing_operation import OfflineProcessingOperation
    from .order import Order
    from .order_adjustment import OrderAdjustment
    from .order_item import OrderItem
    from .order_item_device_condition import OrderItemDeviceCondition
    from .order_item_solution_setup import OrderItemSolutionSetup
    from .order_item_solution_setup_application_settings import OrderItemSolutionSetupApplicationSettings
    from .order_item_solution_setup_application_settings_security import (
        OrderItemSolutionSetupApplicationSettingsSecurity,
    )
    from .order_item_solution_setup_batch_closure import (
        OrderItemSolutionSetupBatchClosure,
        OrderItemSolutionSetupBatchClosure_Automatic,
        OrderItemSolutionSetupBatchClosure_Manual,
    )
    from .order_item_solution_setup_device_settings import OrderItemSolutionSetupDeviceSettings
    from .order_item_solution_setup_device_settings_communication_type import (
        OrderItemSolutionSetupDeviceSettingsCommunicationType,
    )
    from .order_item_solution_setup_gateway_settings import OrderItemSolutionSetupGatewaySettings
    from .order_item_solution_setup_receipt_notifications import OrderItemSolutionSetupReceiptNotifications
    from .order_item_solution_setup_taxes_item import OrderItemSolutionSetupTaxesItem
    from .order_item_solution_setup_tips import OrderItemSolutionSetupTips
    from .order_item_type import OrderItemType
    from .owner import Owner
    from .owner_relationship import OwnerRelationship
    from .pad_bank_account import PadBankAccount
    from .pad_payload import PadPayload
    from .pad_payload_account_type import PadPayloadAccountType
    from .pad_source import PadSource
    from .pad_source_with_account_type import PadSourceWithAccountType
    from .pad_source_with_account_type_account_type import PadSourceWithAccountTypeAccountType
    from .paginated_contacts import PaginatedContacts
    from .paginated_event_subscriptions import PaginatedEventSubscriptions
    from .paginated_fund_recipients import PaginatedFundRecipients
    from .paginated_list import PaginatedList
    from .paginated_merchants import PaginatedMerchants
    from .paginated_owners import PaginatedOwners
    from .paginated_pricing_intent import PaginatedPricingIntent
    from .paginated_processing_accounts import PaginatedProcessingAccounts
    from .paginated_processing_terminals import PaginatedProcessingTerminals
    from .partially_encrypted_keyed_data_format import PartiallyEncryptedKeyedDataFormat
    from .patch_add import PatchAdd
    from .patch_copy import PatchCopy
    from .patch_document import (
        PatchDocument,
        PatchDocument_Add,
        PatchDocument_Copy,
        PatchDocument_Move,
        PatchDocument_Remove,
        PatchDocument_Replace,
        PatchDocument_Test,
    )
    from .patch_move import PatchMove
    from .patch_remove import PatchRemove
    from .patch_replace import PatchReplace
    from .patch_request import PatchRequest
    from .patch_test import PatchTest
    from .payment import Payment
    from .payment_instruction import PaymentInstruction
    from .payment_instruction_order import PaymentInstructionOrder
    from .payment_link_assets import PaymentLinkAssets
    from .payment_link_email_recipient import PaymentLinkEmailRecipient
    from .payment_link_email_share_event import PaymentLinkEmailShareEvent
    from .payment_link_email_share_event_sharing_method import PaymentLinkEmailShareEventSharingMethod
    from .payment_link_paginated_list import PaymentLinkPaginatedList
    from .payment_link_paginated_list_data_item import (
        PaymentLinkPaginatedListDataItem,
        PaymentLinkPaginatedListDataItem_MultiUse,
        PaymentLinkPaginatedListDataItem_SingleUse,
    )
    from .payment_method_ach import PaymentMethodAch
    from .payment_method_ach_value import PaymentMethodAchValue
    from .payment_methods import PaymentMethods
    from .payment_methods_item import PaymentMethodsItem, PaymentMethodsItem_Ach
    from .payment_order import PaymentOrder
    from .payment_order_base import PaymentOrderBase
    from .payment_order_request import PaymentOrderRequest
    from .payment_paginated_list_for_read import PaymentPaginatedListForRead
    from .payment_plan import PaymentPlan
    from .payment_plan_base import PaymentPlanBase
    from .payment_plan_base_frequency import PaymentPlanBaseFrequency
    from .payment_plan_base_on_delete import PaymentPlanBaseOnDelete
    from .payment_plan_base_on_update import PaymentPlanBaseOnUpdate
    from .payment_plan_base_type import PaymentPlanBaseType
    from .payment_plan_order_breakdown import PaymentPlanOrderBreakdown
    from .payment_plan_order_breakdown_base import PaymentPlanOrderBreakdownBase
    from .payment_plan_paginated_list import PaymentPlanPaginatedList
    from .payment_plan_recurring_order import PaymentPlanRecurringOrder
    from .payment_plan_recurring_order_base import PaymentPlanRecurringOrderBase
    from .payment_plan_setup_order import PaymentPlanSetupOrder
    from .payment_plan_setup_order_base import PaymentPlanSetupOrderBase
    from .payment_plan_summary import PaymentPlanSummary
    from .payment_summary import PaymentSummary
    from .payment_summary_response_code import PaymentSummaryResponseCode
    from .payment_summary_status import PaymentSummaryStatus
    from .payroc_gateway import PayrocGateway
    from .payroc_gateway_gateway import PayrocGatewayGateway
    from .percentage import Percentage
    from .pin_debit import PinDebit
    from .plain_text_keyed_data_format import PlainTextKeyedDataFormat
    from .plain_text_swiped_data_format import PlainTextSwipedDataFormat
    from .plain_text_swiped_data_format_fallback_reason import PlainTextSwipedDataFormatFallbackReason
    from .preset_payment_link_charge import PresetPaymentLinkCharge
    from .pricing import Pricing, Pricing_Agreement, Pricing_Intent
    from .pricing_agreement import PricingAgreement
    from .pricing_agreement_reminder import PricingAgreementReminder
    from .pricing_agreement_us_40 import PricingAgreementUs40
    from .pricing_agreement_us_40_country import PricingAgreementUs40Country
    from .pricing_agreement_us_40_processor import PricingAgreementUs40Processor
    from .pricing_agreement_us_40_processor_card import (
        PricingAgreementUs40ProcessorCard,
        PricingAgreementUs40ProcessorCard_ConsumerChoice,
        PricingAgreementUs40ProcessorCard_FlatRate,
        PricingAgreementUs40ProcessorCard_InterchangePlus,
        PricingAgreementUs40ProcessorCard_InterchangePlusTiered3,
        PricingAgreementUs40ProcessorCard_RewardPay,
        PricingAgreementUs40ProcessorCard_RewardPayChoice,
        PricingAgreementUs40ProcessorCard_Tiered3,
        PricingAgreementUs40ProcessorCard_Tiered4,
        PricingAgreementUs40ProcessorCard_Tiered6,
    )
    from .pricing_agreement_us_40_version import PricingAgreementUs40Version
    from .pricing_agreement_us_50 import PricingAgreementUs50
    from .pricing_agreement_us_50_country import PricingAgreementUs50Country
    from .pricing_agreement_us_50_processor import PricingAgreementUs50Processor
    from .pricing_agreement_us_50_processor_card import (
        PricingAgreementUs50ProcessorCard,
        PricingAgreementUs50ProcessorCard_ConsumerChoice,
        PricingAgreementUs50ProcessorCard_FlatRate,
        PricingAgreementUs50ProcessorCard_InterchangePlus,
        PricingAgreementUs50ProcessorCard_InterchangePlusPlus,
        PricingAgreementUs50ProcessorCard_RewardPayChoice,
        PricingAgreementUs50ProcessorCard_Tiered3,
        PricingAgreementUs50ProcessorCard_Tiered4,
        PricingAgreementUs50ProcessorCard_Tiered6,
    )
    from .pricing_agreement_us_50_version import PricingAgreementUs50Version
    from .pricing_intent import PricingIntent
    from .pricing_intent_50 import PricingIntent50
    from .pricing_template import PricingTemplate
    from .processing import Processing
    from .processing_account import ProcessingAccount
    from .processing_account_business_type import ProcessingAccountBusinessType
    from .processing_account_contacts_item import ProcessingAccountContactsItem
    from .processing_account_contacts_item_link import ProcessingAccountContactsItemLink
    from .processing_account_owners_item import ProcessingAccountOwnersItem
    from .processing_account_owners_item_link import ProcessingAccountOwnersItemLink
    from .processing_account_pricing import ProcessingAccountPricing
    from .processing_account_pricing_link import ProcessingAccountPricingLink
    from .processing_account_status import ProcessingAccountStatus
    from .processing_ach import ProcessingAch
    from .processing_ach_limits import ProcessingAchLimits
    from .processing_ach_refunds import ProcessingAchRefunds
    from .processing_ach_transaction_types_item import ProcessingAchTransactionTypesItem
    from .processing_card_acceptance import ProcessingCardAcceptance
    from .processing_card_acceptance_cards_accepted_item import ProcessingCardAcceptanceCardsAcceptedItem
    from .processing_card_acceptance_speciality_cards import ProcessingCardAcceptanceSpecialityCards
    from .processing_card_acceptance_speciality_cards_american_express_direct import (
        ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect,
    )
    from .processing_card_acceptance_speciality_cards_electronic_benefits_transfer import (
        ProcessingCardAcceptanceSpecialityCardsElectronicBenefitsTransfer,
    )
    from .processing_card_acceptance_speciality_cards_other import ProcessingCardAcceptanceSpecialityCardsOther
    from .processing_monthly_amounts import ProcessingMonthlyAmounts
    from .processing_months_of_operation_item import ProcessingMonthsOfOperationItem
    from .processing_terminal import ProcessingTerminal
    from .processing_terminal_application_settings import ProcessingTerminalApplicationSettings
    from .processing_terminal_batch_closure import (
        ProcessingTerminalBatchClosure,
        ProcessingTerminalBatchClosure_Automatic,
        ProcessingTerminalBatchClosure_Manual,
    )
    from .processing_terminal_devices_item import ProcessingTerminalDevicesItem
    from .processing_terminal_features import ProcessingTerminalFeatures
    from .processing_terminal_features_ebt import ProcessingTerminalFeaturesEbt
    from .processing_terminal_features_enhanced_processing import ProcessingTerminalFeaturesEnhancedProcessing
    from .processing_terminal_features_enhanced_processing_shipping_address_mode import (
        ProcessingTerminalFeaturesEnhancedProcessingShippingAddressMode,
    )
    from .processing_terminal_features_enhanced_processing_transaction_data_level import (
        ProcessingTerminalFeaturesEnhancedProcessingTransactionDataLevel,
    )
    from .processing_terminal_features_payment_links import ProcessingTerminalFeaturesPaymentLinks
    from .processing_terminal_features_tips import ProcessingTerminalFeaturesTips
    from .processing_terminal_receipt_notifications import ProcessingTerminalReceiptNotifications
    from .processing_terminal_security import ProcessingTerminalSecurity
    from .processing_terminal_security_avs_level import ProcessingTerminalSecurityAvsLevel
    from .processing_terminal_status import ProcessingTerminalStatus
    from .processing_terminal_summary import ProcessingTerminalSummary
    from .processing_terminal_summary_link import ProcessingTerminalSummaryLink
    from .processing_terminal_taxes_item import ProcessingTerminalTaxesItem
    from .processing_terminal_timezone import ProcessingTerminalTimezone
    from .processing_transaction_amounts import ProcessingTransactionAmounts
    from .processing_volume_breakdown import ProcessingVolumeBreakdown
    from .processor_fee import ProcessorFee
    from .prompt_payment_link_charge import PromptPaymentLinkCharge
    from .qual_rates import QualRates
    from .qual_rates_with_premium import QualRatesWithPremium
    from .qual_rates_with_premium_and_regulated import QualRatesWithPremiumAndRegulated
    from .raw_card_details import RawCardDetails
    from .raw_card_details_downgrade_to import RawCardDetailsDowngradeTo
    from .raw_pin_details import RawPinDetails
    from .refund_instruction import RefundInstruction
    from .refund_instruction_order import RefundInstructionOrder
    from .refund_order import RefundOrder
    from .refund_paginated_list import RefundPaginatedList
    from .refund_summary import RefundSummary
    from .refund_summary_response_code import RefundSummaryResponseCode
    from .refund_summary_status import RefundSummaryStatus
    from .retrieved_address import RetrievedAddress
    from .retrieved_card import RetrievedCard
    from .retrieved_card_entry_method import RetrievedCardEntryMethod
    from .retrieved_customer import RetrievedCustomer
    from .retrieved_customer_notification_language import RetrievedCustomerNotificationLanguage
    from .retrieved_payment import RetrievedPayment
    from .retrieved_refund import RetrievedRefund
    from .retrieved_shipping import RetrievedShipping
    from .retrieved_tax import RetrievedTax
    from .reward_pay import RewardPay
    from .reward_pay_choice import RewardPayChoice
    from .reward_pay_choice_fees import RewardPayChoiceFees
    from .reward_pay_choice_fees_credit import RewardPayChoiceFeesCredit
    from .reward_pay_choice_fees_credit_tips import RewardPayChoiceFeesCreditTips
    from .reward_pay_choice_fees_debit import RewardPayChoiceFeesDebit
    from .reward_pay_choice_fees_debit_option import RewardPayChoiceFeesDebitOption
    from .reward_pay_fees import RewardPayFees
    from .reward_pay_fees_tips import RewardPayFeesTips
    from .schemas_automatic_batch_close import SchemasAutomaticBatchClose
    from .schemas_credential_on_file import SchemasCredentialOnFile
    from .schemas_credential_on_file_mit_agreement import SchemasCredentialOnFileMitAgreement
    from .schemas_manual_batch_close import SchemasManualBatchClose
    from .schemas_timezone import SchemasTimezone
    from .secure_token import SecureToken
    from .secure_token_mit_agreement import SecureTokenMitAgreement
    from .secure_token_paginated_list_with_account_type import SecureTokenPaginatedListWithAccountType
    from .secure_token_payload import SecureTokenPayload
    from .secure_token_payload_account_type import SecureTokenPayloadAccountType
    from .secure_token_payload_sec_code import SecureTokenPayloadSecCode
    from .secure_token_source import (
        SecureTokenSource,
        SecureTokenSource_Ach,
        SecureTokenSource_Card,
        SecureTokenSource_Pad,
    )
    from .secure_token_status import SecureTokenStatus
    from .secure_token_summary import SecureTokenSummary
    from .secure_token_summary_status import SecureTokenSummaryStatus
    from .secure_token_with_account_type import SecureTokenWithAccountType
    from .secure_token_with_account_type_source import (
        SecureTokenWithAccountTypeSource,
        SecureTokenWithAccountTypeSource_Ach,
        SecureTokenWithAccountTypeSource_Card,
        SecureTokenWithAccountTypeSource_Pad,
    )
    from .security_check import SecurityCheck
    from .security_check_avs_result import SecurityCheckAvsResult
    from .security_check_cvv_result import SecurityCheckCvvResult
    from .service_us_50 import ServiceUs50, ServiceUs50_HardwareAdvantagePlan
    from .services_us_50 import ServicesUs50
    from .settled_summary import SettledSummary
    from .sharing_event_paginated_list import SharingEventPaginatedList
    from .shipping import Shipping
    from .signature import Signature, Signature_RequestedViaDirectLink, Signature_RequestedViaEmail
    from .signature_adjustment import SignatureAdjustment
    from .signature_by_direct_link import SignatureByDirectLink
    from .signature_by_email import SignatureByEmail
    from .signature_instruction import SignatureInstruction
    from .single_use_payment_link import SingleUsePaymentLink
    from .single_use_payment_link_auth_type import SingleUsePaymentLinkAuthType
    from .single_use_payment_link_order import SingleUsePaymentLinkOrder
    from .single_use_payment_link_order_charge import (
        SingleUsePaymentLinkOrderCharge,
        SingleUsePaymentLinkOrderCharge_Preset,
        SingleUsePaymentLinkOrderCharge_Prompt,
    )
    from .single_use_payment_link_payment_methods_item import SingleUsePaymentLinkPaymentMethodsItem
    from .single_use_payment_link_status import SingleUsePaymentLinkStatus
    from .single_use_token import SingleUseToken
    from .single_use_token_account_update import SingleUseTokenAccountUpdate
    from .single_use_token_payload import SingleUseTokenPayload
    from .single_use_token_payload_account_type import SingleUseTokenPayloadAccountType
    from .single_use_token_payload_pin_details import (
        SingleUseTokenPayloadPinDetails,
        SingleUseTokenPayloadPinDetails_Dukpt,
        SingleUseTokenPayloadPinDetails_Raw,
    )
    from .single_use_token_payload_sec_code import SingleUseTokenPayloadSecCode
    from .single_use_token_payment_method import SingleUseTokenPaymentMethod, SingleUseTokenPaymentMethod_Card
    from .single_use_token_source import (
        SingleUseTokenSource,
        SingleUseTokenSource_Ach,
        SingleUseTokenSource_Card,
        SingleUseTokenSource_Pad,
    )
    from .speciality_cards import SpecialityCards
    from .standing_instructions import StandingInstructions
    from .standing_instructions_processing_model import StandingInstructionsProcessingModel
    from .standing_instructions_sequence import StandingInstructionsSequence
    from .status_adjustment import StatusAdjustment
    from .status_adjustment_to_status import StatusAdjustmentToStatus
    from .subscription import Subscription
    from .subscription_frequency import SubscriptionFrequency
    from .subscription_order_breakdown import SubscriptionOrderBreakdown
    from .subscription_order_breakdown_base import SubscriptionOrderBreakdownBase
    from .subscription_order_breakdown_request import SubscriptionOrderBreakdownRequest
    from .subscription_paginated_list import SubscriptionPaginatedList
    from .subscription_payment import SubscriptionPayment
    from .subscription_payment_order import SubscriptionPaymentOrder
    from .subscription_payment_order_base import SubscriptionPaymentOrderBase
    from .subscription_payment_order_request import SubscriptionPaymentOrderRequest
    from .subscription_recurring_order import SubscriptionRecurringOrder
    from .subscription_recurring_order_base import SubscriptionRecurringOrderBase
    from .subscription_recurring_order_request import SubscriptionRecurringOrderRequest
    from .subscription_state import SubscriptionState
    from .subscription_state_status import SubscriptionStateStatus
    from .subscription_type import SubscriptionType
    from .supported_operations import SupportedOperations
    from .supported_operations_item import SupportedOperationsItem
    from .surcharge import Surcharge
    from .surcharging import Surcharging
    from .swiped_card_details import SwipedCardDetails
    from .swiped_card_details_downgrade_to import SwipedCardDetailsDowngradeTo
    from .swiped_card_details_pin_details import SwipedCardDetailsPinDetails, SwipedCardDetailsPinDetails_Dukpt
    from .swiped_card_details_swiped_data import (
        SwipedCardDetailsSwipedData,
        SwipedCardDetailsSwipedData_Encrypted,
        SwipedCardDetailsSwipedData_PlainText,
    )
    from .tax import Tax, Tax_Amount, Tax_Rate
    from .tax_amount import TaxAmount
    from .tax_rate import TaxRate
    from .tax_rate_type import TaxRateType
    from .terminal_order import TerminalOrder
    from .terminal_order_order_items_item import TerminalOrderOrderItemsItem
    from .terminal_order_shipping import TerminalOrderShipping
    from .terminal_order_shipping_address import TerminalOrderShippingAddress
    from .terminal_order_shipping_preferences import TerminalOrderShippingPreferences
    from .terminal_order_shipping_preferences_method import TerminalOrderShippingPreferencesMethod
    from .terminal_order_status import TerminalOrderStatus
    from .terminal_order_training_provider import TerminalOrderTrainingProvider
    from .third_party_three_d_secure import ThirdPartyThreeDSecure
    from .third_party_three_d_secure_eci import ThirdPartyThreeDSecureEci
    from .tiered_3 import Tiered3
    from .tiered_3_amex_direct import Tiered3AmexDirect
    from .tiered_3_amex_opt_blue import Tiered3AmexOptBlue
    from .tiered_3_fees import Tiered3Fees
    from .tiered_3_fees_amex import Tiered3FeesAmex, Tiered3FeesAmex_Direct, Tiered3FeesAmex_OptBlue
    from .tiered_4 import Tiered4
    from .tiered_4_amex_direct import Tiered4AmexDirect
    from .tiered_4_amex_opt_blue import Tiered4AmexOptBlue
    from .tiered_4_fees import Tiered4Fees
    from .tiered_4_fees_amex import Tiered4FeesAmex, Tiered4FeesAmex_Direct, Tiered4FeesAmex_OptBlue
    from .tiered_6 import Tiered6
    from .tiered_6_amex_direct import Tiered6AmexDirect
    from .tiered_6_amex_opt_blue import Tiered6AmexOptBlue
    from .tiered_6_fees import Tiered6Fees
    from .tiered_6_fees_amex import Tiered6FeesAmex, Tiered6FeesAmex_Direct, Tiered6FeesAmex_OptBlue
    from .timezone import Timezone
    from .tip import Tip
    from .tip_mode import TipMode
    from .tip_processing_disabled import TipProcessingDisabled
    from .tip_processing_enabled import TipProcessingEnabled
    from .tip_processing_enabled_suggested_tips import TipProcessingEnabledSuggestedTips
    from .tip_type import TipType
    from .training_provider import TrainingProvider
    from .transaction import Transaction
    from .transaction_entry_method import TransactionEntryMethod
    from .transaction_interchange import TransactionInterchange
    from .transaction_result import TransactionResult
    from .transaction_result_ebt_type import TransactionResultEbtType
    from .transaction_result_response_code import TransactionResultResponseCode
    from .transaction_result_status import TransactionResultStatus
    from .transaction_result_type import TransactionResultType
    from .transaction_status import TransactionStatus
    from .transaction_summary import TransactionSummary
    from .transaction_summary_entry_method import TransactionSummaryEntryMethod
    from .transaction_summary_type import TransactionSummaryType
    from .transaction_type import TransactionType
    from .tsys import Tsys
    from .tsys_merchant import TsysMerchant
    from .tsys_terminal import TsysTerminal
    from .unit_of_measure import UnitOfMeasure
    from .voucher import Voucher
    from .webhook import Webhook
_dynamic_imports: typing.Dict[str, str] = {
    "AccountUpdate": ".account_update",
    "AccountUpdate_SingleUseToken": ".account_update",
    "Ach": ".ach",
    "AchBankAccount": ".ach_bank_account",
    "AchBankAccountSecCode": ".ach_bank_account_sec_code",
    "AchDeposit": ".ach_deposit",
    "AchDepositFee": ".ach_deposit_fee",
    "AchDepositSummary": ".ach_deposit_summary",
    "AchFees": ".ach_fees",
    "AchPayload": ".ach_payload",
    "AchPayloadAccountType": ".ach_payload_account_type",
    "AchPayloadSecCode": ".ach_payload_sec_code",
    "AchSource": ".ach_source",
    "AchSourceWithAccountType": ".ach_source_with_account_type",
    "AchSourceWithAccountTypeAccountType": ".ach_source_with_account_type_account_type",
    "ActivityRecord": ".activity_record",
    "ActivityRecordType": ".activity_record_type",
    "Address": ".address",
    "AddressType": ".address_type",
    "AddressTypeType": ".address_type_type",
    "Amount": ".amount",
    "ApplePayResponseSession": ".apple_pay_response_session",
    "Authorization": ".authorization",
    "AuthorizationAuthorizationResponse": ".authorization_authorization_response",
    "AuthorizationSummary": ".authorization_summary",
    "AutomaticBatchClose": ".automatic_batch_close",
    "Balance": ".balance",
    "BalanceResponseCode": ".balance_response_code",
    "BankAccountVerificationResult": ".bank_account_verification_result",
    "BankTransferBreakdown": ".bank_transfer_breakdown",
    "BankTransferBreakdownBase": ".bank_transfer_breakdown_base",
    "BankTransferCustomer": ".bank_transfer_customer",
    "BankTransferCustomerNotificationLanguage": ".bank_transfer_customer_notification_language",
    "BankTransferPayment": ".bank_transfer_payment",
    "BankTransferPaymentBankAccount": ".bank_transfer_payment_bank_account",
    "BankTransferPaymentBankAccount_Ach": ".bank_transfer_payment_bank_account",
    "BankTransferPaymentBankAccount_Pad": ".bank_transfer_payment_bank_account",
    "BankTransferPaymentOrder": ".bank_transfer_payment_order",
    "BankTransferPaymentOrderBase": ".bank_transfer_payment_order_base",
    "BankTransferPaymentPaginatedList": ".bank_transfer_payment_paginated_list",
    "BankTransferPaymentRequestOrder": ".bank_transfer_payment_request_order",
    "BankTransferRefund": ".bank_transfer_refund",
    "BankTransferRefundBankAccount": ".bank_transfer_refund_bank_account",
    "BankTransferRefundBankAccount_Ach": ".bank_transfer_refund_bank_account",
    "BankTransferRefundBankAccount_Pad": ".bank_transfer_refund_bank_account",
    "BankTransferRefundOrder": ".bank_transfer_refund_order",
    "BankTransferRefundPaginatedList": ".bank_transfer_refund_paginated_list",
    "BankTransferRequestBreakdown": ".bank_transfer_request_breakdown",
    "BankTransferResult": ".bank_transfer_result",
    "BankTransferResultStatus": ".bank_transfer_result_status",
    "BankTransferResultType": ".bank_transfer_result_type",
    "BankTransferReturnSummary": ".bank_transfer_return_summary",
    "BaseIntent": ".base_intent",
    "BaseIntentStatus": ".base_intent_status",
    "BaseUs": ".base_us",
    "BaseUsAnnual": ".base_us_annual",
    "BaseUsAnnualFee": ".base_us_annual_fee",
    "BaseUsAnnualFeeBillInMonth": ".base_us_annual_fee_bill_in_month",
    "BaseUsMonthly": ".base_us_monthly",
    "BaseUsPlatinumSecurity": ".base_us_platinum_security",
    "BaseUsPlatinumSecurity_Annual": ".base_us_platinum_security",
    "BaseUsPlatinumSecurity_Monthly": ".base_us_platinum_security",
    "Batch": ".batch",
    "BatchSummary": ".batch_summary",
    "Breakdown": ".breakdown",
    "BreakdownAdjustment": ".breakdown_adjustment",
    "BreakdownBase": ".breakdown_base",
    "BreakdownForPaymentInstructions": ".breakdown_for_payment_instructions",
    "BreakdownRequest": ".breakdown_request",
    "Business": ".business",
    "BusinessCountryOfOperation": ".business_country_of_operation",
    "BusinessOrganizationType": ".business_organization_type",
    "Card": ".card",
    "CardBalance": ".card_balance",
    "CardBalanceBenefitCategory": ".card_balance_benefit_category",
    "CardBinPayload": ".card_bin_payload",
    "CardEntryMethod": ".card_entry_method",
    "CardInfo": ".card_info",
    "CardPayload": ".card_payload",
    "CardPayloadAccountType": ".card_payload_account_type",
    "CardPayloadCardDetails": ".card_payload_card_details",
    "CardPayloadCardDetails_Icc": ".card_payload_card_details",
    "CardPayloadCardDetails_Keyed": ".card_payload_card_details",
    "CardPayloadCardDetails_Raw": ".card_payload_card_details",
    "CardPayloadCardDetails_Swiped": ".card_payload_card_details",
    "CardSource": ".card_source",
    "CardSummary": ".card_summary",
    "CardSummaryType": ".card_summary_type",
    "CardVerificationResult": ".card_verification_result",
    "ChoiceRate": ".choice_rate",
    "CommonFunding": ".common_funding",
    "CommonFundingFundingSchedule": ".common_funding_funding_schedule",
    "CommonFundingStatus": ".common_funding_status",
    "CommunicationType": ".communication_type",
    "ConsumerChoice": ".consumer_choice",
    "ConsumerChoiceFees": ".consumer_choice_fees",
    "Contact": ".contact",
    "ContactMethod": ".contact_method",
    "ContactMethodEmail": ".contact_method_email",
    "ContactMethodFax": ".contact_method_fax",
    "ContactMethodMobile": ".contact_method_mobile",
    "ContactMethodPhone": ".contact_method_phone",
    "ContactMethod_Email": ".contact_method",
    "ContactMethod_Fax": ".contact_method",
    "ContactMethod_Mobile": ".contact_method",
    "ContactMethod_Phone": ".contact_method",
    "ContactType": ".contact_type",
    "ConvenienceFee": ".convenience_fee",
    "CreateFunding": ".create_funding",
    "CreateProcessingAccount": ".create_processing_account",
    "CreateProcessingAccountBusinessType": ".create_processing_account_business_type",
    "CredentialOnFile": ".credential_on_file",
    "CredentialOnFileMitAgreement": ".credential_on_file_mit_agreement",
    "Currency": ".currency",
    "CustomField": ".custom_field",
    "CustomLabel": ".custom_label",
    "CustomLabelElement": ".custom_label_element",
    "Customer": ".customer",
    "CustomerAdjustment": ".customer_adjustment",
    "CustomerNotificationLanguage": ".customer_notification_language",
    "CustomizationOptions": ".customization_options",
    "CustomizationOptionsEntryMethod": ".customization_options_entry_method",
    "DccOffer": ".dcc_offer",
    "Device": ".device",
    "DeviceCategory": ".device_category",
    "DeviceConfig": ".device_config",
    "DeviceInstruction": ".device_instruction",
    "DeviceInstructionStatus": ".device_instruction_status",
    "DeviceModel": ".device_model",
    "DigitalWalletPayload": ".digital_wallet_payload",
    "DigitalWalletPayloadAccountType": ".digital_wallet_payload_account_type",
    "DigitalWalletPayloadServiceProvider": ".digital_wallet_payload_service_provider",
    "Dispute": ".dispute",
    "DisputeCurrentStatus": ".dispute_current_status",
    "DisputeDisputeType": ".dispute_dispute_type",
    "DisputeStatus": ".dispute_status",
    "DisputeStatusStatus": ".dispute_status_status",
    "DualPricing": ".dual_pricing",
    "DualPricingAlternativeTender": ".dual_pricing_alternative_tender",
    "DukptPinDetails": ".dukpt_pin_details",
    "EbtDetails": ".ebt_details",
    "EbtDetailsBenefitCategory": ".ebt_details_benefit_category",
    "EbtDetailsWithVoucher": ".ebt_details_with_voucher",
    "EbtDisabled": ".ebt_disabled",
    "EbtEnabled": ".ebt_enabled",
    "EbtEnabledEbtType": ".ebt_enabled_ebt_type",
    "ElectronicBenefitsTransfer": ".electronic_benefits_transfer",
    "EmvTag": ".emv_tag",
    "EncryptedSwipedDataFormat": ".encrypted_swiped_data_format",
    "EncryptedSwipedDataFormatFallbackReason": ".encrypted_swiped_data_format_fallback_reason",
    "EncryptionCapableDevice": ".encryption_capable_device",
    "EnhancedInterchange": ".enhanced_interchange",
    "EventSubscription": ".event_subscription",
    "EventSubscriptionStatus": ".event_subscription_status",
    "FirstTxnReferenceData": ".first_txn_reference_data",
    "FiveHundred": ".five_hundred",
    "FiveHundredErrorsItem": ".five_hundred_errors_item",
    "FlatRate": ".flat_rate",
    "FlatRateAmexDirect": ".flat_rate_amex_direct",
    "FlatRateFees": ".flat_rate_fees",
    "FlatRateFeesAmex": ".flat_rate_fees_amex",
    "FlatRateFeesAmex_Direct": ".flat_rate_fees_amex",
    "FourHundred": ".four_hundred",
    "FourHundredErrorsItem": ".four_hundred_errors_item",
    "FourHundredFifteen": ".four_hundred_fifteen",
    "FourHundredFour": ".four_hundred_four",
    "FourHundredNine": ".four_hundred_nine",
    "FourHundredNineErrorsItem": ".four_hundred_nine_errors_item",
    "FourHundredOne": ".four_hundred_one",
    "FourHundredSix": ".four_hundred_six",
    "FourHundredThirteen": ".four_hundred_thirteen",
    "FourHundredThree": ".four_hundred_three",
    "FullyEncryptedKeyedDataFormat": ".fully_encrypted_keyed_data_format",
    "FundingAccount": ".funding_account",
    "FundingAccountStatus": ".funding_account_status",
    "FundingAccountSummary": ".funding_account_summary",
    "FundingAccountSummaryStatus": ".funding_account_summary_status",
    "FundingAccountType": ".funding_account_type",
    "FundingAccountUse": ".funding_account_use",
    "FundingRecipient": ".funding_recipient",
    "FundingRecipientFundingAccountsItem": ".funding_recipient_funding_accounts_item",
    "FundingRecipientFundingAccountsItemLink": ".funding_recipient_funding_accounts_item_link",
    "FundingRecipientFundingAccountsItemStatus": ".funding_recipient_funding_accounts_item_status",
    "FundingRecipientOwnersItem": ".funding_recipient_owners_item",
    "FundingRecipientOwnersItemLink": ".funding_recipient_owners_item_link",
    "FundingRecipientRecipientType": ".funding_recipient_recipient_type",
    "FundingRecipientStatus": ".funding_recipient_status",
    "FxRate": ".fx_rate",
    "FxRateInquiryResult": ".fx_rate_inquiry_result",
    "GatewayThreeDSecure": ".gateway_three_d_secure",
    "GatewayUs": ".gateway_us",
    "GatewayUs50": ".gateway_us_50",
    "GatewayUs50Fees": ".gateway_us_50_fees",
    "GatewayUsFees": ".gateway_us_fees",
    "HardwareAdvantagePlan": ".hardware_advantage_plan",
    "HostConfiguration": ".host_configuration",
    "HostConfigurationConfiguration": ".host_configuration_configuration",
    "HostConfigurationConfiguration_Tsys": ".host_configuration_configuration",
    "HostedFieldsCreateSessionResponse": ".hosted_fields_create_session_response",
    "IccCardDetails": ".icc_card_details",
    "IccCardDetailsDowngradeTo": ".icc_card_details_downgrade_to",
    "Identifier": ".identifier",
    "IdentifierType": ".identifier_type",
    "Instruction": ".instruction",
    "InstructionMerchantsItem": ".instruction_merchants_item",
    "InstructionMerchantsItemLink": ".instruction_merchants_item_link",
    "InstructionMerchantsItemRecipientsItem": ".instruction_merchants_item_recipients_item",
    "InstructionMerchantsItemRecipientsItemAmount": ".instruction_merchants_item_recipients_item_amount",
    "InstructionMerchantsItemRecipientsItemAmountCurrency": ".instruction_merchants_item_recipients_item_amount_currency",
    "InstructionMerchantsItemRecipientsItemLink": ".instruction_merchants_item_recipients_item_link",
    "InstructionMerchantsItemRecipientsItemPaymentMethod": ".instruction_merchants_item_recipients_item_payment_method",
    "InstructionMerchantsItemRecipientsItemStatus": ".instruction_merchants_item_recipients_item_status",
    "InstructionStatus": ".instruction_status",
    "InterchangePlus": ".interchange_plus",
    "InterchangePlusAmexDirect": ".interchange_plus_amex_direct",
    "InterchangePlusAmexOptBlue": ".interchange_plus_amex_opt_blue",
    "InterchangePlusFees": ".interchange_plus_fees",
    "InterchangePlusFeesAmex": ".interchange_plus_fees_amex",
    "InterchangePlusFeesAmex_Direct": ".interchange_plus_fees_amex",
    "InterchangePlusFeesAmex_OptBlue": ".interchange_plus_fees_amex",
    "InterchangePlusPlus": ".interchange_plus_plus",
    "InterchangePlusPlusAmexDirect": ".interchange_plus_plus_amex_direct",
    "InterchangePlusPlusAmexOptBlue": ".interchange_plus_plus_amex_opt_blue",
    "InterchangePlusPlusFees": ".interchange_plus_plus_fees",
    "InterchangePlusPlusFeesAmex": ".interchange_plus_plus_fees_amex",
    "InterchangePlusPlusFeesAmex_Direct": ".interchange_plus_plus_fees_amex",
    "InterchangePlusPlusFeesAmex_OptBlue": ".interchange_plus_plus_fees_amex",
    "InterchangePlusTiered3": ".interchange_plus_tiered_3",
    "InterchangePlusTiered3AmexDirect": ".interchange_plus_tiered_3_amex_direct",
    "InterchangePlusTiered3AmexOptBlue": ".interchange_plus_tiered_3_amex_opt_blue",
    "InterchangePlusTiered3Fees": ".interchange_plus_tiered_3_fees",
    "InterchangePlusTiered3FeesAmex": ".interchange_plus_tiered_3_fees_amex",
    "InterchangePlusTiered3FeesAmex_Direct": ".interchange_plus_tiered_3_fees_amex",
    "InterchangePlusTiered3FeesAmex_OptBlue": ".interchange_plus_tiered_3_fees_amex",
    "IpAddress": ".ip_address",
    "IpAddressType": ".ip_address_type",
    "ItemizedBreakdown": ".itemized_breakdown",
    "ItemizedBreakdownRequest": ".itemized_breakdown_request",
    "KeyedCardDetails": ".keyed_card_details",
    "KeyedCardDetailsKeyedData": ".keyed_card_details_keyed_data",
    "KeyedCardDetailsKeyedData_FullyEncrypted": ".keyed_card_details_keyed_data",
    "KeyedCardDetailsKeyedData_PartiallyEncrypted": ".keyed_card_details_keyed_data",
    "KeyedCardDetailsKeyedData_PlainText": ".keyed_card_details_keyed_data",
    "KeyedCardDetailsPinDetails": ".keyed_card_details_pin_details",
    "KeyedCardDetailsPinDetails_Dukpt": ".keyed_card_details_pin_details",
    "LegalAddress": ".legal_address",
    "LineItem": ".line_item",
    "LineItemBase": ".line_item_base",
    "LineItemRequest": ".line_item_request",
    "Link": ".link",
    "Links": ".links",
    "ListFundingAccounts": ".list_funding_accounts",
    "ManualBatchClose": ".manual_batch_close",
    "MerchantBalance": ".merchant_balance",
    "MerchantPlatform": ".merchant_platform",
    "MerchantPlatformProcessingAccountsItem": ".merchant_platform_processing_accounts_item",
    "MerchantPlatformProcessingAccountsItemLink": ".merchant_platform_processing_accounts_item_link",
    "MerchantPlatformProcessingAccountsItemStatus": ".merchant_platform_processing_accounts_item_status",
    "MerchantSummary": ".merchant_summary",
    "MultiUsePaymentLink": ".multi_use_payment_link",
    "MultiUsePaymentLinkAuthType": ".multi_use_payment_link_auth_type",
    "MultiUsePaymentLinkOrder": ".multi_use_payment_link_order",
    "MultiUsePaymentLinkOrderCharge": ".multi_use_payment_link_order_charge",
    "MultiUsePaymentLinkOrderCharge_Preset": ".multi_use_payment_link_order_charge",
    "MultiUsePaymentLinkOrderCharge_Prompt": ".multi_use_payment_link_order_charge",
    "MultiUsePaymentLinkPaymentMethodsItem": ".multi_use_payment_link_payment_methods_item",
    "MultiUsePaymentLinkStatus": ".multi_use_payment_link_status",
    "Notification": ".notification",
    "Notification_Webhook": ".notification",
    "OfflineProcessing": ".offline_processing",
    "OfflineProcessingOperation": ".offline_processing_operation",
    "Order": ".order",
    "OrderAdjustment": ".order_adjustment",
    "OrderItem": ".order_item",
    "OrderItemDeviceCondition": ".order_item_device_condition",
    "OrderItemSolutionSetup": ".order_item_solution_setup",
    "OrderItemSolutionSetupApplicationSettings": ".order_item_solution_setup_application_settings",
    "OrderItemSolutionSetupApplicationSettingsSecurity": ".order_item_solution_setup_application_settings_security",
    "OrderItemSolutionSetupBatchClosure": ".order_item_solution_setup_batch_closure",
    "OrderItemSolutionSetupBatchClosure_Automatic": ".order_item_solution_setup_batch_closure",
    "OrderItemSolutionSetupBatchClosure_Manual": ".order_item_solution_setup_batch_closure",
    "OrderItemSolutionSetupDeviceSettings": ".order_item_solution_setup_device_settings",
    "OrderItemSolutionSetupDeviceSettingsCommunicationType": ".order_item_solution_setup_device_settings_communication_type",
    "OrderItemSolutionSetupGatewaySettings": ".order_item_solution_setup_gateway_settings",
    "OrderItemSolutionSetupReceiptNotifications": ".order_item_solution_setup_receipt_notifications",
    "OrderItemSolutionSetupTaxesItem": ".order_item_solution_setup_taxes_item",
    "OrderItemSolutionSetupTips": ".order_item_solution_setup_tips",
    "OrderItemType": ".order_item_type",
    "Owner": ".owner",
    "OwnerRelationship": ".owner_relationship",
    "PadBankAccount": ".pad_bank_account",
    "PadPayload": ".pad_payload",
    "PadPayloadAccountType": ".pad_payload_account_type",
    "PadSource": ".pad_source",
    "PadSourceWithAccountType": ".pad_source_with_account_type",
    "PadSourceWithAccountTypeAccountType": ".pad_source_with_account_type_account_type",
    "PaginatedContacts": ".paginated_contacts",
    "PaginatedEventSubscriptions": ".paginated_event_subscriptions",
    "PaginatedFundRecipients": ".paginated_fund_recipients",
    "PaginatedList": ".paginated_list",
    "PaginatedMerchants": ".paginated_merchants",
    "PaginatedOwners": ".paginated_owners",
    "PaginatedPricingIntent": ".paginated_pricing_intent",
    "PaginatedProcessingAccounts": ".paginated_processing_accounts",
    "PaginatedProcessingTerminals": ".paginated_processing_terminals",
    "PartiallyEncryptedKeyedDataFormat": ".partially_encrypted_keyed_data_format",
    "PatchAdd": ".patch_add",
    "PatchCopy": ".patch_copy",
    "PatchDocument": ".patch_document",
    "PatchDocument_Add": ".patch_document",
    "PatchDocument_Copy": ".patch_document",
    "PatchDocument_Move": ".patch_document",
    "PatchDocument_Remove": ".patch_document",
    "PatchDocument_Replace": ".patch_document",
    "PatchDocument_Test": ".patch_document",
    "PatchMove": ".patch_move",
    "PatchRemove": ".patch_remove",
    "PatchReplace": ".patch_replace",
    "PatchRequest": ".patch_request",
    "PatchTest": ".patch_test",
    "Payment": ".payment",
    "PaymentInstruction": ".payment_instruction",
    "PaymentInstructionOrder": ".payment_instruction_order",
    "PaymentLinkAssets": ".payment_link_assets",
    "PaymentLinkEmailRecipient": ".payment_link_email_recipient",
    "PaymentLinkEmailShareEvent": ".payment_link_email_share_event",
    "PaymentLinkEmailShareEventSharingMethod": ".payment_link_email_share_event_sharing_method",
    "PaymentLinkPaginatedList": ".payment_link_paginated_list",
    "PaymentLinkPaginatedListDataItem": ".payment_link_paginated_list_data_item",
    "PaymentLinkPaginatedListDataItem_MultiUse": ".payment_link_paginated_list_data_item",
    "PaymentLinkPaginatedListDataItem_SingleUse": ".payment_link_paginated_list_data_item",
    "PaymentMethodAch": ".payment_method_ach",
    "PaymentMethodAchValue": ".payment_method_ach_value",
    "PaymentMethods": ".payment_methods",
    "PaymentMethodsItem": ".payment_methods_item",
    "PaymentMethodsItem_Ach": ".payment_methods_item",
    "PaymentOrder": ".payment_order",
    "PaymentOrderBase": ".payment_order_base",
    "PaymentOrderRequest": ".payment_order_request",
    "PaymentPaginatedListForRead": ".payment_paginated_list_for_read",
    "PaymentPlan": ".payment_plan",
    "PaymentPlanBase": ".payment_plan_base",
    "PaymentPlanBaseFrequency": ".payment_plan_base_frequency",
    "PaymentPlanBaseOnDelete": ".payment_plan_base_on_delete",
    "PaymentPlanBaseOnUpdate": ".payment_plan_base_on_update",
    "PaymentPlanBaseType": ".payment_plan_base_type",
    "PaymentPlanOrderBreakdown": ".payment_plan_order_breakdown",
    "PaymentPlanOrderBreakdownBase": ".payment_plan_order_breakdown_base",
    "PaymentPlanPaginatedList": ".payment_plan_paginated_list",
    "PaymentPlanRecurringOrder": ".payment_plan_recurring_order",
    "PaymentPlanRecurringOrderBase": ".payment_plan_recurring_order_base",
    "PaymentPlanSetupOrder": ".payment_plan_setup_order",
    "PaymentPlanSetupOrderBase": ".payment_plan_setup_order_base",
    "PaymentPlanSummary": ".payment_plan_summary",
    "PaymentSummary": ".payment_summary",
    "PaymentSummaryResponseCode": ".payment_summary_response_code",
    "PaymentSummaryStatus": ".payment_summary_status",
    "PayrocGateway": ".payroc_gateway",
    "PayrocGatewayGateway": ".payroc_gateway_gateway",
    "Percentage": ".percentage",
    "PinDebit": ".pin_debit",
    "PlainTextKeyedDataFormat": ".plain_text_keyed_data_format",
    "PlainTextSwipedDataFormat": ".plain_text_swiped_data_format",
    "PlainTextSwipedDataFormatFallbackReason": ".plain_text_swiped_data_format_fallback_reason",
    "PresetPaymentLinkCharge": ".preset_payment_link_charge",
    "Pricing": ".pricing",
    "PricingAgreement": ".pricing_agreement",
    "PricingAgreementReminder": ".pricing_agreement_reminder",
    "PricingAgreementUs40": ".pricing_agreement_us_40",
    "PricingAgreementUs40Country": ".pricing_agreement_us_40_country",
    "PricingAgreementUs40Processor": ".pricing_agreement_us_40_processor",
    "PricingAgreementUs40ProcessorCard": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_ConsumerChoice": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_FlatRate": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_InterchangePlus": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_InterchangePlusTiered3": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_RewardPay": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_RewardPayChoice": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_Tiered3": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_Tiered4": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40ProcessorCard_Tiered6": ".pricing_agreement_us_40_processor_card",
    "PricingAgreementUs40Version": ".pricing_agreement_us_40_version",
    "PricingAgreementUs50": ".pricing_agreement_us_50",
    "PricingAgreementUs50Country": ".pricing_agreement_us_50_country",
    "PricingAgreementUs50Processor": ".pricing_agreement_us_50_processor",
    "PricingAgreementUs50ProcessorCard": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_ConsumerChoice": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_FlatRate": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_InterchangePlus": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_InterchangePlusPlus": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_RewardPayChoice": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_Tiered3": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_Tiered4": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50ProcessorCard_Tiered6": ".pricing_agreement_us_50_processor_card",
    "PricingAgreementUs50Version": ".pricing_agreement_us_50_version",
    "PricingIntent": ".pricing_intent",
    "PricingIntent50": ".pricing_intent_50",
    "PricingTemplate": ".pricing_template",
    "Pricing_Agreement": ".pricing",
    "Pricing_Intent": ".pricing",
    "Processing": ".processing",
    "ProcessingAccount": ".processing_account",
    "ProcessingAccountBusinessType": ".processing_account_business_type",
    "ProcessingAccountContactsItem": ".processing_account_contacts_item",
    "ProcessingAccountContactsItemLink": ".processing_account_contacts_item_link",
    "ProcessingAccountOwnersItem": ".processing_account_owners_item",
    "ProcessingAccountOwnersItemLink": ".processing_account_owners_item_link",
    "ProcessingAccountPricing": ".processing_account_pricing",
    "ProcessingAccountPricingLink": ".processing_account_pricing_link",
    "ProcessingAccountStatus": ".processing_account_status",
    "ProcessingAch": ".processing_ach",
    "ProcessingAchLimits": ".processing_ach_limits",
    "ProcessingAchRefunds": ".processing_ach_refunds",
    "ProcessingAchTransactionTypesItem": ".processing_ach_transaction_types_item",
    "ProcessingCardAcceptance": ".processing_card_acceptance",
    "ProcessingCardAcceptanceCardsAcceptedItem": ".processing_card_acceptance_cards_accepted_item",
    "ProcessingCardAcceptanceSpecialityCards": ".processing_card_acceptance_speciality_cards",
    "ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect": ".processing_card_acceptance_speciality_cards_american_express_direct",
    "ProcessingCardAcceptanceSpecialityCardsElectronicBenefitsTransfer": ".processing_card_acceptance_speciality_cards_electronic_benefits_transfer",
    "ProcessingCardAcceptanceSpecialityCardsOther": ".processing_card_acceptance_speciality_cards_other",
    "ProcessingMonthlyAmounts": ".processing_monthly_amounts",
    "ProcessingMonthsOfOperationItem": ".processing_months_of_operation_item",
    "ProcessingTerminal": ".processing_terminal",
    "ProcessingTerminalApplicationSettings": ".processing_terminal_application_settings",
    "ProcessingTerminalBatchClosure": ".processing_terminal_batch_closure",
    "ProcessingTerminalBatchClosure_Automatic": ".processing_terminal_batch_closure",
    "ProcessingTerminalBatchClosure_Manual": ".processing_terminal_batch_closure",
    "ProcessingTerminalDevicesItem": ".processing_terminal_devices_item",
    "ProcessingTerminalFeatures": ".processing_terminal_features",
    "ProcessingTerminalFeaturesEbt": ".processing_terminal_features_ebt",
    "ProcessingTerminalFeaturesEnhancedProcessing": ".processing_terminal_features_enhanced_processing",
    "ProcessingTerminalFeaturesEnhancedProcessingShippingAddressMode": ".processing_terminal_features_enhanced_processing_shipping_address_mode",
    "ProcessingTerminalFeaturesEnhancedProcessingTransactionDataLevel": ".processing_terminal_features_enhanced_processing_transaction_data_level",
    "ProcessingTerminalFeaturesPaymentLinks": ".processing_terminal_features_payment_links",
    "ProcessingTerminalFeaturesTips": ".processing_terminal_features_tips",
    "ProcessingTerminalReceiptNotifications": ".processing_terminal_receipt_notifications",
    "ProcessingTerminalSecurity": ".processing_terminal_security",
    "ProcessingTerminalSecurityAvsLevel": ".processing_terminal_security_avs_level",
    "ProcessingTerminalStatus": ".processing_terminal_status",
    "ProcessingTerminalSummary": ".processing_terminal_summary",
    "ProcessingTerminalSummaryLink": ".processing_terminal_summary_link",
    "ProcessingTerminalTaxesItem": ".processing_terminal_taxes_item",
    "ProcessingTerminalTimezone": ".processing_terminal_timezone",
    "ProcessingTransactionAmounts": ".processing_transaction_amounts",
    "ProcessingVolumeBreakdown": ".processing_volume_breakdown",
    "ProcessorFee": ".processor_fee",
    "PromptPaymentLinkCharge": ".prompt_payment_link_charge",
    "QualRates": ".qual_rates",
    "QualRatesWithPremium": ".qual_rates_with_premium",
    "QualRatesWithPremiumAndRegulated": ".qual_rates_with_premium_and_regulated",
    "RawCardDetails": ".raw_card_details",
    "RawCardDetailsDowngradeTo": ".raw_card_details_downgrade_to",
    "RawPinDetails": ".raw_pin_details",
    "RefundInstruction": ".refund_instruction",
    "RefundInstructionOrder": ".refund_instruction_order",
    "RefundOrder": ".refund_order",
    "RefundPaginatedList": ".refund_paginated_list",
    "RefundSummary": ".refund_summary",
    "RefundSummaryResponseCode": ".refund_summary_response_code",
    "RefundSummaryStatus": ".refund_summary_status",
    "RetrievedAddress": ".retrieved_address",
    "RetrievedCard": ".retrieved_card",
    "RetrievedCardEntryMethod": ".retrieved_card_entry_method",
    "RetrievedCustomer": ".retrieved_customer",
    "RetrievedCustomerNotificationLanguage": ".retrieved_customer_notification_language",
    "RetrievedPayment": ".retrieved_payment",
    "RetrievedRefund": ".retrieved_refund",
    "RetrievedShipping": ".retrieved_shipping",
    "RetrievedTax": ".retrieved_tax",
    "RewardPay": ".reward_pay",
    "RewardPayChoice": ".reward_pay_choice",
    "RewardPayChoiceFees": ".reward_pay_choice_fees",
    "RewardPayChoiceFeesCredit": ".reward_pay_choice_fees_credit",
    "RewardPayChoiceFeesCreditTips": ".reward_pay_choice_fees_credit_tips",
    "RewardPayChoiceFeesDebit": ".reward_pay_choice_fees_debit",
    "RewardPayChoiceFeesDebitOption": ".reward_pay_choice_fees_debit_option",
    "RewardPayFees": ".reward_pay_fees",
    "RewardPayFeesTips": ".reward_pay_fees_tips",
    "SchemasAutomaticBatchClose": ".schemas_automatic_batch_close",
    "SchemasCredentialOnFile": ".schemas_credential_on_file",
    "SchemasCredentialOnFileMitAgreement": ".schemas_credential_on_file_mit_agreement",
    "SchemasManualBatchClose": ".schemas_manual_batch_close",
    "SchemasTimezone": ".schemas_timezone",
    "SecureToken": ".secure_token",
    "SecureTokenMitAgreement": ".secure_token_mit_agreement",
    "SecureTokenPaginatedListWithAccountType": ".secure_token_paginated_list_with_account_type",
    "SecureTokenPayload": ".secure_token_payload",
    "SecureTokenPayloadAccountType": ".secure_token_payload_account_type",
    "SecureTokenPayloadSecCode": ".secure_token_payload_sec_code",
    "SecureTokenSource": ".secure_token_source",
    "SecureTokenSource_Ach": ".secure_token_source",
    "SecureTokenSource_Card": ".secure_token_source",
    "SecureTokenSource_Pad": ".secure_token_source",
    "SecureTokenStatus": ".secure_token_status",
    "SecureTokenSummary": ".secure_token_summary",
    "SecureTokenSummaryStatus": ".secure_token_summary_status",
    "SecureTokenWithAccountType": ".secure_token_with_account_type",
    "SecureTokenWithAccountTypeSource": ".secure_token_with_account_type_source",
    "SecureTokenWithAccountTypeSource_Ach": ".secure_token_with_account_type_source",
    "SecureTokenWithAccountTypeSource_Card": ".secure_token_with_account_type_source",
    "SecureTokenWithAccountTypeSource_Pad": ".secure_token_with_account_type_source",
    "SecurityCheck": ".security_check",
    "SecurityCheckAvsResult": ".security_check_avs_result",
    "SecurityCheckCvvResult": ".security_check_cvv_result",
    "ServiceUs50": ".service_us_50",
    "ServiceUs50_HardwareAdvantagePlan": ".service_us_50",
    "ServicesUs50": ".services_us_50",
    "SettledSummary": ".settled_summary",
    "SharingEventPaginatedList": ".sharing_event_paginated_list",
    "Shipping": ".shipping",
    "Signature": ".signature",
    "SignatureAdjustment": ".signature_adjustment",
    "SignatureByDirectLink": ".signature_by_direct_link",
    "SignatureByEmail": ".signature_by_email",
    "SignatureInstruction": ".signature_instruction",
    "Signature_RequestedViaDirectLink": ".signature",
    "Signature_RequestedViaEmail": ".signature",
    "SingleUsePaymentLink": ".single_use_payment_link",
    "SingleUsePaymentLinkAuthType": ".single_use_payment_link_auth_type",
    "SingleUsePaymentLinkOrder": ".single_use_payment_link_order",
    "SingleUsePaymentLinkOrderCharge": ".single_use_payment_link_order_charge",
    "SingleUsePaymentLinkOrderCharge_Preset": ".single_use_payment_link_order_charge",
    "SingleUsePaymentLinkOrderCharge_Prompt": ".single_use_payment_link_order_charge",
    "SingleUsePaymentLinkPaymentMethodsItem": ".single_use_payment_link_payment_methods_item",
    "SingleUsePaymentLinkStatus": ".single_use_payment_link_status",
    "SingleUseToken": ".single_use_token",
    "SingleUseTokenAccountUpdate": ".single_use_token_account_update",
    "SingleUseTokenPayload": ".single_use_token_payload",
    "SingleUseTokenPayloadAccountType": ".single_use_token_payload_account_type",
    "SingleUseTokenPayloadPinDetails": ".single_use_token_payload_pin_details",
    "SingleUseTokenPayloadPinDetails_Dukpt": ".single_use_token_payload_pin_details",
    "SingleUseTokenPayloadPinDetails_Raw": ".single_use_token_payload_pin_details",
    "SingleUseTokenPayloadSecCode": ".single_use_token_payload_sec_code",
    "SingleUseTokenPaymentMethod": ".single_use_token_payment_method",
    "SingleUseTokenPaymentMethod_Card": ".single_use_token_payment_method",
    "SingleUseTokenSource": ".single_use_token_source",
    "SingleUseTokenSource_Ach": ".single_use_token_source",
    "SingleUseTokenSource_Card": ".single_use_token_source",
    "SingleUseTokenSource_Pad": ".single_use_token_source",
    "SpecialityCards": ".speciality_cards",
    "StandingInstructions": ".standing_instructions",
    "StandingInstructionsProcessingModel": ".standing_instructions_processing_model",
    "StandingInstructionsSequence": ".standing_instructions_sequence",
    "StatusAdjustment": ".status_adjustment",
    "StatusAdjustmentToStatus": ".status_adjustment_to_status",
    "Subscription": ".subscription",
    "SubscriptionFrequency": ".subscription_frequency",
    "SubscriptionOrderBreakdown": ".subscription_order_breakdown",
    "SubscriptionOrderBreakdownBase": ".subscription_order_breakdown_base",
    "SubscriptionOrderBreakdownRequest": ".subscription_order_breakdown_request",
    "SubscriptionPaginatedList": ".subscription_paginated_list",
    "SubscriptionPayment": ".subscription_payment",
    "SubscriptionPaymentOrder": ".subscription_payment_order",
    "SubscriptionPaymentOrderBase": ".subscription_payment_order_base",
    "SubscriptionPaymentOrderRequest": ".subscription_payment_order_request",
    "SubscriptionRecurringOrder": ".subscription_recurring_order",
    "SubscriptionRecurringOrderBase": ".subscription_recurring_order_base",
    "SubscriptionRecurringOrderRequest": ".subscription_recurring_order_request",
    "SubscriptionState": ".subscription_state",
    "SubscriptionStateStatus": ".subscription_state_status",
    "SubscriptionType": ".subscription_type",
    "SupportedOperations": ".supported_operations",
    "SupportedOperationsItem": ".supported_operations_item",
    "Surcharge": ".surcharge",
    "Surcharging": ".surcharging",
    "SwipedCardDetails": ".swiped_card_details",
    "SwipedCardDetailsDowngradeTo": ".swiped_card_details_downgrade_to",
    "SwipedCardDetailsPinDetails": ".swiped_card_details_pin_details",
    "SwipedCardDetailsPinDetails_Dukpt": ".swiped_card_details_pin_details",
    "SwipedCardDetailsSwipedData": ".swiped_card_details_swiped_data",
    "SwipedCardDetailsSwipedData_Encrypted": ".swiped_card_details_swiped_data",
    "SwipedCardDetailsSwipedData_PlainText": ".swiped_card_details_swiped_data",
    "Tax": ".tax",
    "TaxAmount": ".tax_amount",
    "TaxRate": ".tax_rate",
    "TaxRateType": ".tax_rate_type",
    "Tax_Amount": ".tax",
    "Tax_Rate": ".tax",
    "TerminalOrder": ".terminal_order",
    "TerminalOrderOrderItemsItem": ".terminal_order_order_items_item",
    "TerminalOrderShipping": ".terminal_order_shipping",
    "TerminalOrderShippingAddress": ".terminal_order_shipping_address",
    "TerminalOrderShippingPreferences": ".terminal_order_shipping_preferences",
    "TerminalOrderShippingPreferencesMethod": ".terminal_order_shipping_preferences_method",
    "TerminalOrderStatus": ".terminal_order_status",
    "TerminalOrderTrainingProvider": ".terminal_order_training_provider",
    "ThirdPartyThreeDSecure": ".third_party_three_d_secure",
    "ThirdPartyThreeDSecureEci": ".third_party_three_d_secure_eci",
    "Tiered3": ".tiered_3",
    "Tiered3AmexDirect": ".tiered_3_amex_direct",
    "Tiered3AmexOptBlue": ".tiered_3_amex_opt_blue",
    "Tiered3Fees": ".tiered_3_fees",
    "Tiered3FeesAmex": ".tiered_3_fees_amex",
    "Tiered3FeesAmex_Direct": ".tiered_3_fees_amex",
    "Tiered3FeesAmex_OptBlue": ".tiered_3_fees_amex",
    "Tiered4": ".tiered_4",
    "Tiered4AmexDirect": ".tiered_4_amex_direct",
    "Tiered4AmexOptBlue": ".tiered_4_amex_opt_blue",
    "Tiered4Fees": ".tiered_4_fees",
    "Tiered4FeesAmex": ".tiered_4_fees_amex",
    "Tiered4FeesAmex_Direct": ".tiered_4_fees_amex",
    "Tiered4FeesAmex_OptBlue": ".tiered_4_fees_amex",
    "Tiered6": ".tiered_6",
    "Tiered6AmexDirect": ".tiered_6_amex_direct",
    "Tiered6AmexOptBlue": ".tiered_6_amex_opt_blue",
    "Tiered6Fees": ".tiered_6_fees",
    "Tiered6FeesAmex": ".tiered_6_fees_amex",
    "Tiered6FeesAmex_Direct": ".tiered_6_fees_amex",
    "Tiered6FeesAmex_OptBlue": ".tiered_6_fees_amex",
    "Timezone": ".timezone",
    "Tip": ".tip",
    "TipMode": ".tip_mode",
    "TipProcessingDisabled": ".tip_processing_disabled",
    "TipProcessingEnabled": ".tip_processing_enabled",
    "TipProcessingEnabledSuggestedTips": ".tip_processing_enabled_suggested_tips",
    "TipType": ".tip_type",
    "TrainingProvider": ".training_provider",
    "Transaction": ".transaction",
    "TransactionEntryMethod": ".transaction_entry_method",
    "TransactionInterchange": ".transaction_interchange",
    "TransactionResult": ".transaction_result",
    "TransactionResultEbtType": ".transaction_result_ebt_type",
    "TransactionResultResponseCode": ".transaction_result_response_code",
    "TransactionResultStatus": ".transaction_result_status",
    "TransactionResultType": ".transaction_result_type",
    "TransactionStatus": ".transaction_status",
    "TransactionSummary": ".transaction_summary",
    "TransactionSummaryEntryMethod": ".transaction_summary_entry_method",
    "TransactionSummaryType": ".transaction_summary_type",
    "TransactionType": ".transaction_type",
    "Tsys": ".tsys",
    "TsysMerchant": ".tsys_merchant",
    "TsysTerminal": ".tsys_terminal",
    "UnitOfMeasure": ".unit_of_measure",
    "Voucher": ".voucher",
    "Webhook": ".webhook",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AccountUpdate",
    "AccountUpdate_SingleUseToken",
    "Ach",
    "AchBankAccount",
    "AchBankAccountSecCode",
    "AchDeposit",
    "AchDepositFee",
    "AchDepositSummary",
    "AchFees",
    "AchPayload",
    "AchPayloadAccountType",
    "AchPayloadSecCode",
    "AchSource",
    "AchSourceWithAccountType",
    "AchSourceWithAccountTypeAccountType",
    "ActivityRecord",
    "ActivityRecordType",
    "Address",
    "AddressType",
    "AddressTypeType",
    "Amount",
    "ApplePayResponseSession",
    "Authorization",
    "AuthorizationAuthorizationResponse",
    "AuthorizationSummary",
    "AutomaticBatchClose",
    "Balance",
    "BalanceResponseCode",
    "BankAccountVerificationResult",
    "BankTransferBreakdown",
    "BankTransferBreakdownBase",
    "BankTransferCustomer",
    "BankTransferCustomerNotificationLanguage",
    "BankTransferPayment",
    "BankTransferPaymentBankAccount",
    "BankTransferPaymentBankAccount_Ach",
    "BankTransferPaymentBankAccount_Pad",
    "BankTransferPaymentOrder",
    "BankTransferPaymentOrderBase",
    "BankTransferPaymentPaginatedList",
    "BankTransferPaymentRequestOrder",
    "BankTransferRefund",
    "BankTransferRefundBankAccount",
    "BankTransferRefundBankAccount_Ach",
    "BankTransferRefundBankAccount_Pad",
    "BankTransferRefundOrder",
    "BankTransferRefundPaginatedList",
    "BankTransferRequestBreakdown",
    "BankTransferResult",
    "BankTransferResultStatus",
    "BankTransferResultType",
    "BankTransferReturnSummary",
    "BaseIntent",
    "BaseIntentStatus",
    "BaseUs",
    "BaseUsAnnual",
    "BaseUsAnnualFee",
    "BaseUsAnnualFeeBillInMonth",
    "BaseUsMonthly",
    "BaseUsPlatinumSecurity",
    "BaseUsPlatinumSecurity_Annual",
    "BaseUsPlatinumSecurity_Monthly",
    "Batch",
    "BatchSummary",
    "Breakdown",
    "BreakdownAdjustment",
    "BreakdownBase",
    "BreakdownForPaymentInstructions",
    "BreakdownRequest",
    "Business",
    "BusinessCountryOfOperation",
    "BusinessOrganizationType",
    "Card",
    "CardBalance",
    "CardBalanceBenefitCategory",
    "CardBinPayload",
    "CardEntryMethod",
    "CardInfo",
    "CardPayload",
    "CardPayloadAccountType",
    "CardPayloadCardDetails",
    "CardPayloadCardDetails_Icc",
    "CardPayloadCardDetails_Keyed",
    "CardPayloadCardDetails_Raw",
    "CardPayloadCardDetails_Swiped",
    "CardSource",
    "CardSummary",
    "CardSummaryType",
    "CardVerificationResult",
    "ChoiceRate",
    "CommonFunding",
    "CommonFundingFundingSchedule",
    "CommonFundingStatus",
    "CommunicationType",
    "ConsumerChoice",
    "ConsumerChoiceFees",
    "Contact",
    "ContactMethod",
    "ContactMethodEmail",
    "ContactMethodFax",
    "ContactMethodMobile",
    "ContactMethodPhone",
    "ContactMethod_Email",
    "ContactMethod_Fax",
    "ContactMethod_Mobile",
    "ContactMethod_Phone",
    "ContactType",
    "ConvenienceFee",
    "CreateFunding",
    "CreateProcessingAccount",
    "CreateProcessingAccountBusinessType",
    "CredentialOnFile",
    "CredentialOnFileMitAgreement",
    "Currency",
    "CustomField",
    "CustomLabel",
    "CustomLabelElement",
    "Customer",
    "CustomerAdjustment",
    "CustomerNotificationLanguage",
    "CustomizationOptions",
    "CustomizationOptionsEntryMethod",
    "DccOffer",
    "Device",
    "DeviceCategory",
    "DeviceConfig",
    "DeviceInstruction",
    "DeviceInstructionStatus",
    "DeviceModel",
    "DigitalWalletPayload",
    "DigitalWalletPayloadAccountType",
    "DigitalWalletPayloadServiceProvider",
    "Dispute",
    "DisputeCurrentStatus",
    "DisputeDisputeType",
    "DisputeStatus",
    "DisputeStatusStatus",
    "DualPricing",
    "DualPricingAlternativeTender",
    "DukptPinDetails",
    "EbtDetails",
    "EbtDetailsBenefitCategory",
    "EbtDetailsWithVoucher",
    "EbtDisabled",
    "EbtEnabled",
    "EbtEnabledEbtType",
    "ElectronicBenefitsTransfer",
    "EmvTag",
    "EncryptedSwipedDataFormat",
    "EncryptedSwipedDataFormatFallbackReason",
    "EncryptionCapableDevice",
    "EnhancedInterchange",
    "EventSubscription",
    "EventSubscriptionStatus",
    "FirstTxnReferenceData",
    "FiveHundred",
    "FiveHundredErrorsItem",
    "FlatRate",
    "FlatRateAmexDirect",
    "FlatRateFees",
    "FlatRateFeesAmex",
    "FlatRateFeesAmex_Direct",
    "FourHundred",
    "FourHundredErrorsItem",
    "FourHundredFifteen",
    "FourHundredFour",
    "FourHundredNine",
    "FourHundredNineErrorsItem",
    "FourHundredOne",
    "FourHundredSix",
    "FourHundredThirteen",
    "FourHundredThree",
    "FullyEncryptedKeyedDataFormat",
    "FundingAccount",
    "FundingAccountStatus",
    "FundingAccountSummary",
    "FundingAccountSummaryStatus",
    "FundingAccountType",
    "FundingAccountUse",
    "FundingRecipient",
    "FundingRecipientFundingAccountsItem",
    "FundingRecipientFundingAccountsItemLink",
    "FundingRecipientFundingAccountsItemStatus",
    "FundingRecipientOwnersItem",
    "FundingRecipientOwnersItemLink",
    "FundingRecipientRecipientType",
    "FundingRecipientStatus",
    "FxRate",
    "FxRateInquiryResult",
    "GatewayThreeDSecure",
    "GatewayUs",
    "GatewayUs50",
    "GatewayUs50Fees",
    "GatewayUsFees",
    "HardwareAdvantagePlan",
    "HostConfiguration",
    "HostConfigurationConfiguration",
    "HostConfigurationConfiguration_Tsys",
    "HostedFieldsCreateSessionResponse",
    "IccCardDetails",
    "IccCardDetailsDowngradeTo",
    "Identifier",
    "IdentifierType",
    "Instruction",
    "InstructionMerchantsItem",
    "InstructionMerchantsItemLink",
    "InstructionMerchantsItemRecipientsItem",
    "InstructionMerchantsItemRecipientsItemAmount",
    "InstructionMerchantsItemRecipientsItemAmountCurrency",
    "InstructionMerchantsItemRecipientsItemLink",
    "InstructionMerchantsItemRecipientsItemPaymentMethod",
    "InstructionMerchantsItemRecipientsItemStatus",
    "InstructionStatus",
    "InterchangePlus",
    "InterchangePlusAmexDirect",
    "InterchangePlusAmexOptBlue",
    "InterchangePlusFees",
    "InterchangePlusFeesAmex",
    "InterchangePlusFeesAmex_Direct",
    "InterchangePlusFeesAmex_OptBlue",
    "InterchangePlusPlus",
    "InterchangePlusPlusAmexDirect",
    "InterchangePlusPlusAmexOptBlue",
    "InterchangePlusPlusFees",
    "InterchangePlusPlusFeesAmex",
    "InterchangePlusPlusFeesAmex_Direct",
    "InterchangePlusPlusFeesAmex_OptBlue",
    "InterchangePlusTiered3",
    "InterchangePlusTiered3AmexDirect",
    "InterchangePlusTiered3AmexOptBlue",
    "InterchangePlusTiered3Fees",
    "InterchangePlusTiered3FeesAmex",
    "InterchangePlusTiered3FeesAmex_Direct",
    "InterchangePlusTiered3FeesAmex_OptBlue",
    "IpAddress",
    "IpAddressType",
    "ItemizedBreakdown",
    "ItemizedBreakdownRequest",
    "KeyedCardDetails",
    "KeyedCardDetailsKeyedData",
    "KeyedCardDetailsKeyedData_FullyEncrypted",
    "KeyedCardDetailsKeyedData_PartiallyEncrypted",
    "KeyedCardDetailsKeyedData_PlainText",
    "KeyedCardDetailsPinDetails",
    "KeyedCardDetailsPinDetails_Dukpt",
    "LegalAddress",
    "LineItem",
    "LineItemBase",
    "LineItemRequest",
    "Link",
    "Links",
    "ListFundingAccounts",
    "ManualBatchClose",
    "MerchantBalance",
    "MerchantPlatform",
    "MerchantPlatformProcessingAccountsItem",
    "MerchantPlatformProcessingAccountsItemLink",
    "MerchantPlatformProcessingAccountsItemStatus",
    "MerchantSummary",
    "MultiUsePaymentLink",
    "MultiUsePaymentLinkAuthType",
    "MultiUsePaymentLinkOrder",
    "MultiUsePaymentLinkOrderCharge",
    "MultiUsePaymentLinkOrderCharge_Preset",
    "MultiUsePaymentLinkOrderCharge_Prompt",
    "MultiUsePaymentLinkPaymentMethodsItem",
    "MultiUsePaymentLinkStatus",
    "Notification",
    "Notification_Webhook",
    "OfflineProcessing",
    "OfflineProcessingOperation",
    "Order",
    "OrderAdjustment",
    "OrderItem",
    "OrderItemDeviceCondition",
    "OrderItemSolutionSetup",
    "OrderItemSolutionSetupApplicationSettings",
    "OrderItemSolutionSetupApplicationSettingsSecurity",
    "OrderItemSolutionSetupBatchClosure",
    "OrderItemSolutionSetupBatchClosure_Automatic",
    "OrderItemSolutionSetupBatchClosure_Manual",
    "OrderItemSolutionSetupDeviceSettings",
    "OrderItemSolutionSetupDeviceSettingsCommunicationType",
    "OrderItemSolutionSetupGatewaySettings",
    "OrderItemSolutionSetupReceiptNotifications",
    "OrderItemSolutionSetupTaxesItem",
    "OrderItemSolutionSetupTips",
    "OrderItemType",
    "Owner",
    "OwnerRelationship",
    "PadBankAccount",
    "PadPayload",
    "PadPayloadAccountType",
    "PadSource",
    "PadSourceWithAccountType",
    "PadSourceWithAccountTypeAccountType",
    "PaginatedContacts",
    "PaginatedEventSubscriptions",
    "PaginatedFundRecipients",
    "PaginatedList",
    "PaginatedMerchants",
    "PaginatedOwners",
    "PaginatedPricingIntent",
    "PaginatedProcessingAccounts",
    "PaginatedProcessingTerminals",
    "PartiallyEncryptedKeyedDataFormat",
    "PatchAdd",
    "PatchCopy",
    "PatchDocument",
    "PatchDocument_Add",
    "PatchDocument_Copy",
    "PatchDocument_Move",
    "PatchDocument_Remove",
    "PatchDocument_Replace",
    "PatchDocument_Test",
    "PatchMove",
    "PatchRemove",
    "PatchReplace",
    "PatchRequest",
    "PatchTest",
    "Payment",
    "PaymentInstruction",
    "PaymentInstructionOrder",
    "PaymentLinkAssets",
    "PaymentLinkEmailRecipient",
    "PaymentLinkEmailShareEvent",
    "PaymentLinkEmailShareEventSharingMethod",
    "PaymentLinkPaginatedList",
    "PaymentLinkPaginatedListDataItem",
    "PaymentLinkPaginatedListDataItem_MultiUse",
    "PaymentLinkPaginatedListDataItem_SingleUse",
    "PaymentMethodAch",
    "PaymentMethodAchValue",
    "PaymentMethods",
    "PaymentMethodsItem",
    "PaymentMethodsItem_Ach",
    "PaymentOrder",
    "PaymentOrderBase",
    "PaymentOrderRequest",
    "PaymentPaginatedListForRead",
    "PaymentPlan",
    "PaymentPlanBase",
    "PaymentPlanBaseFrequency",
    "PaymentPlanBaseOnDelete",
    "PaymentPlanBaseOnUpdate",
    "PaymentPlanBaseType",
    "PaymentPlanOrderBreakdown",
    "PaymentPlanOrderBreakdownBase",
    "PaymentPlanPaginatedList",
    "PaymentPlanRecurringOrder",
    "PaymentPlanRecurringOrderBase",
    "PaymentPlanSetupOrder",
    "PaymentPlanSetupOrderBase",
    "PaymentPlanSummary",
    "PaymentSummary",
    "PaymentSummaryResponseCode",
    "PaymentSummaryStatus",
    "PayrocGateway",
    "PayrocGatewayGateway",
    "Percentage",
    "PinDebit",
    "PlainTextKeyedDataFormat",
    "PlainTextSwipedDataFormat",
    "PlainTextSwipedDataFormatFallbackReason",
    "PresetPaymentLinkCharge",
    "Pricing",
    "PricingAgreement",
    "PricingAgreementReminder",
    "PricingAgreementUs40",
    "PricingAgreementUs40Country",
    "PricingAgreementUs40Processor",
    "PricingAgreementUs40ProcessorCard",
    "PricingAgreementUs40ProcessorCard_ConsumerChoice",
    "PricingAgreementUs40ProcessorCard_FlatRate",
    "PricingAgreementUs40ProcessorCard_InterchangePlus",
    "PricingAgreementUs40ProcessorCard_InterchangePlusTiered3",
    "PricingAgreementUs40ProcessorCard_RewardPay",
    "PricingAgreementUs40ProcessorCard_RewardPayChoice",
    "PricingAgreementUs40ProcessorCard_Tiered3",
    "PricingAgreementUs40ProcessorCard_Tiered4",
    "PricingAgreementUs40ProcessorCard_Tiered6",
    "PricingAgreementUs40Version",
    "PricingAgreementUs50",
    "PricingAgreementUs50Country",
    "PricingAgreementUs50Processor",
    "PricingAgreementUs50ProcessorCard",
    "PricingAgreementUs50ProcessorCard_ConsumerChoice",
    "PricingAgreementUs50ProcessorCard_FlatRate",
    "PricingAgreementUs50ProcessorCard_InterchangePlus",
    "PricingAgreementUs50ProcessorCard_InterchangePlusPlus",
    "PricingAgreementUs50ProcessorCard_RewardPayChoice",
    "PricingAgreementUs50ProcessorCard_Tiered3",
    "PricingAgreementUs50ProcessorCard_Tiered4",
    "PricingAgreementUs50ProcessorCard_Tiered6",
    "PricingAgreementUs50Version",
    "PricingIntent",
    "PricingIntent50",
    "PricingTemplate",
    "Pricing_Agreement",
    "Pricing_Intent",
    "Processing",
    "ProcessingAccount",
    "ProcessingAccountBusinessType",
    "ProcessingAccountContactsItem",
    "ProcessingAccountContactsItemLink",
    "ProcessingAccountOwnersItem",
    "ProcessingAccountOwnersItemLink",
    "ProcessingAccountPricing",
    "ProcessingAccountPricingLink",
    "ProcessingAccountStatus",
    "ProcessingAch",
    "ProcessingAchLimits",
    "ProcessingAchRefunds",
    "ProcessingAchTransactionTypesItem",
    "ProcessingCardAcceptance",
    "ProcessingCardAcceptanceCardsAcceptedItem",
    "ProcessingCardAcceptanceSpecialityCards",
    "ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect",
    "ProcessingCardAcceptanceSpecialityCardsElectronicBenefitsTransfer",
    "ProcessingCardAcceptanceSpecialityCardsOther",
    "ProcessingMonthlyAmounts",
    "ProcessingMonthsOfOperationItem",
    "ProcessingTerminal",
    "ProcessingTerminalApplicationSettings",
    "ProcessingTerminalBatchClosure",
    "ProcessingTerminalBatchClosure_Automatic",
    "ProcessingTerminalBatchClosure_Manual",
    "ProcessingTerminalDevicesItem",
    "ProcessingTerminalFeatures",
    "ProcessingTerminalFeaturesEbt",
    "ProcessingTerminalFeaturesEnhancedProcessing",
    "ProcessingTerminalFeaturesEnhancedProcessingShippingAddressMode",
    "ProcessingTerminalFeaturesEnhancedProcessingTransactionDataLevel",
    "ProcessingTerminalFeaturesPaymentLinks",
    "ProcessingTerminalFeaturesTips",
    "ProcessingTerminalReceiptNotifications",
    "ProcessingTerminalSecurity",
    "ProcessingTerminalSecurityAvsLevel",
    "ProcessingTerminalStatus",
    "ProcessingTerminalSummary",
    "ProcessingTerminalSummaryLink",
    "ProcessingTerminalTaxesItem",
    "ProcessingTerminalTimezone",
    "ProcessingTransactionAmounts",
    "ProcessingVolumeBreakdown",
    "ProcessorFee",
    "PromptPaymentLinkCharge",
    "QualRates",
    "QualRatesWithPremium",
    "QualRatesWithPremiumAndRegulated",
    "RawCardDetails",
    "RawCardDetailsDowngradeTo",
    "RawPinDetails",
    "RefundInstruction",
    "RefundInstructionOrder",
    "RefundOrder",
    "RefundPaginatedList",
    "RefundSummary",
    "RefundSummaryResponseCode",
    "RefundSummaryStatus",
    "RetrievedAddress",
    "RetrievedCard",
    "RetrievedCardEntryMethod",
    "RetrievedCustomer",
    "RetrievedCustomerNotificationLanguage",
    "RetrievedPayment",
    "RetrievedRefund",
    "RetrievedShipping",
    "RetrievedTax",
    "RewardPay",
    "RewardPayChoice",
    "RewardPayChoiceFees",
    "RewardPayChoiceFeesCredit",
    "RewardPayChoiceFeesCreditTips",
    "RewardPayChoiceFeesDebit",
    "RewardPayChoiceFeesDebitOption",
    "RewardPayFees",
    "RewardPayFeesTips",
    "SchemasAutomaticBatchClose",
    "SchemasCredentialOnFile",
    "SchemasCredentialOnFileMitAgreement",
    "SchemasManualBatchClose",
    "SchemasTimezone",
    "SecureToken",
    "SecureTokenMitAgreement",
    "SecureTokenPaginatedListWithAccountType",
    "SecureTokenPayload",
    "SecureTokenPayloadAccountType",
    "SecureTokenPayloadSecCode",
    "SecureTokenSource",
    "SecureTokenSource_Ach",
    "SecureTokenSource_Card",
    "SecureTokenSource_Pad",
    "SecureTokenStatus",
    "SecureTokenSummary",
    "SecureTokenSummaryStatus",
    "SecureTokenWithAccountType",
    "SecureTokenWithAccountTypeSource",
    "SecureTokenWithAccountTypeSource_Ach",
    "SecureTokenWithAccountTypeSource_Card",
    "SecureTokenWithAccountTypeSource_Pad",
    "SecurityCheck",
    "SecurityCheckAvsResult",
    "SecurityCheckCvvResult",
    "ServiceUs50",
    "ServiceUs50_HardwareAdvantagePlan",
    "ServicesUs50",
    "SettledSummary",
    "SharingEventPaginatedList",
    "Shipping",
    "Signature",
    "SignatureAdjustment",
    "SignatureByDirectLink",
    "SignatureByEmail",
    "SignatureInstruction",
    "Signature_RequestedViaDirectLink",
    "Signature_RequestedViaEmail",
    "SingleUsePaymentLink",
    "SingleUsePaymentLinkAuthType",
    "SingleUsePaymentLinkOrder",
    "SingleUsePaymentLinkOrderCharge",
    "SingleUsePaymentLinkOrderCharge_Preset",
    "SingleUsePaymentLinkOrderCharge_Prompt",
    "SingleUsePaymentLinkPaymentMethodsItem",
    "SingleUsePaymentLinkStatus",
    "SingleUseToken",
    "SingleUseTokenAccountUpdate",
    "SingleUseTokenPayload",
    "SingleUseTokenPayloadAccountType",
    "SingleUseTokenPayloadPinDetails",
    "SingleUseTokenPayloadPinDetails_Dukpt",
    "SingleUseTokenPayloadPinDetails_Raw",
    "SingleUseTokenPayloadSecCode",
    "SingleUseTokenPaymentMethod",
    "SingleUseTokenPaymentMethod_Card",
    "SingleUseTokenSource",
    "SingleUseTokenSource_Ach",
    "SingleUseTokenSource_Card",
    "SingleUseTokenSource_Pad",
    "SpecialityCards",
    "StandingInstructions",
    "StandingInstructionsProcessingModel",
    "StandingInstructionsSequence",
    "StatusAdjustment",
    "StatusAdjustmentToStatus",
    "Subscription",
    "SubscriptionFrequency",
    "SubscriptionOrderBreakdown",
    "SubscriptionOrderBreakdownBase",
    "SubscriptionOrderBreakdownRequest",
    "SubscriptionPaginatedList",
    "SubscriptionPayment",
    "SubscriptionPaymentOrder",
    "SubscriptionPaymentOrderBase",
    "SubscriptionPaymentOrderRequest",
    "SubscriptionRecurringOrder",
    "SubscriptionRecurringOrderBase",
    "SubscriptionRecurringOrderRequest",
    "SubscriptionState",
    "SubscriptionStateStatus",
    "SubscriptionType",
    "SupportedOperations",
    "SupportedOperationsItem",
    "Surcharge",
    "Surcharging",
    "SwipedCardDetails",
    "SwipedCardDetailsDowngradeTo",
    "SwipedCardDetailsPinDetails",
    "SwipedCardDetailsPinDetails_Dukpt",
    "SwipedCardDetailsSwipedData",
    "SwipedCardDetailsSwipedData_Encrypted",
    "SwipedCardDetailsSwipedData_PlainText",
    "Tax",
    "TaxAmount",
    "TaxRate",
    "TaxRateType",
    "Tax_Amount",
    "Tax_Rate",
    "TerminalOrder",
    "TerminalOrderOrderItemsItem",
    "TerminalOrderShipping",
    "TerminalOrderShippingAddress",
    "TerminalOrderShippingPreferences",
    "TerminalOrderShippingPreferencesMethod",
    "TerminalOrderStatus",
    "TerminalOrderTrainingProvider",
    "ThirdPartyThreeDSecure",
    "ThirdPartyThreeDSecureEci",
    "Tiered3",
    "Tiered3AmexDirect",
    "Tiered3AmexOptBlue",
    "Tiered3Fees",
    "Tiered3FeesAmex",
    "Tiered3FeesAmex_Direct",
    "Tiered3FeesAmex_OptBlue",
    "Tiered4",
    "Tiered4AmexDirect",
    "Tiered4AmexOptBlue",
    "Tiered4Fees",
    "Tiered4FeesAmex",
    "Tiered4FeesAmex_Direct",
    "Tiered4FeesAmex_OptBlue",
    "Tiered6",
    "Tiered6AmexDirect",
    "Tiered6AmexOptBlue",
    "Tiered6Fees",
    "Tiered6FeesAmex",
    "Tiered6FeesAmex_Direct",
    "Tiered6FeesAmex_OptBlue",
    "Timezone",
    "Tip",
    "TipMode",
    "TipProcessingDisabled",
    "TipProcessingEnabled",
    "TipProcessingEnabledSuggestedTips",
    "TipType",
    "TrainingProvider",
    "Transaction",
    "TransactionEntryMethod",
    "TransactionInterchange",
    "TransactionResult",
    "TransactionResultEbtType",
    "TransactionResultResponseCode",
    "TransactionResultStatus",
    "TransactionResultType",
    "TransactionStatus",
    "TransactionSummary",
    "TransactionSummaryEntryMethod",
    "TransactionSummaryType",
    "TransactionType",
    "Tsys",
    "TsysMerchant",
    "TsysTerminal",
    "UnitOfMeasure",
    "Voucher",
    "Webhook",
]
