# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .ach_source import AchSource
from .ach_source_with_account_type_account_type import AchSourceWithAccountTypeAccountType


class AchSourceWithAccountType(AchSource):
    account_type: typing_extensions.Annotated[
        typing.Optional[AchSourceWithAccountTypeAccountType],
        FieldMetadata(alias="accountType"),
        pydantic.Field(alias="accountType", description="Indicates the customer's account type."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
