# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class AchDepositSummary(UniversalBaseModel):
    """
    Object that contains information about the ACH deposit.
    """

    ach_deposit_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="achDepositId"),
        pydantic.Field(alias="achDepositId", description="Unique identifier of the ACH deposit."),
    ] = None
    link: typing.Optional[Link] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
