# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .bank_transfer_breakdown_base import BankTransferBreakdownBase
from .tax_rate import TaxRate


class BankTransferRequestBreakdown(BankTransferBreakdownBase):
    """
    Object that contains information about the transaction.
    """

    taxes: typing.Optional[typing.List[TaxRate]] = pydantic.Field(default=None)
    """
    Array of tax objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
