# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .currency import Currency


class BankTransferPaymentOrderBase(UniversalBaseModel):
    """
    Object that contains information about the transaction.
    """

    order_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="orderId")] = pydantic.Field(
        default=None
    )
    """
    A unique identifier assigned by the merchant.
    """

    date_time: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="dateTime")] = (
        pydantic.Field(default=None)
    )
    """
    The processing date and time of the transaction represented as per [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A brief description of the transaction.
    """

    amount: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total amount in the currency's lowest denomination. For example, cents.
    """

    currency: typing.Optional[Currency] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
