# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bank_transfer_customer import BankTransferCustomer
from .bank_transfer_refund_bank_account import BankTransferRefundBankAccount
from .bank_transfer_refund_order import BankTransferRefundOrder
from .bank_transfer_result import BankTransferResult
from .custom_field import CustomField
from .payment_summary import PaymentSummary


class BankTransferRefund(UniversalBaseModel):
    refund_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="refundId"),
        pydantic.Field(alias="refundId", description="Unique identifier that our gateway assigned to the refund."),
    ]
    processing_terminal_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="processingTerminalId"),
        pydantic.Field(alias="processingTerminalId", description="Unique identifier that we assigned to the terminal."),
    ]
    order: BankTransferRefundOrder
    customer: typing.Optional[BankTransferCustomer] = None
    bank_account: typing_extensions.Annotated[
        BankTransferRefundBankAccount,
        FieldMetadata(alias="bankAccount"),
        pydantic.Field(
            alias="bankAccount",
            description="Polymorphic object that contains bank account information.  \n\nThe value of the type field determines which variant you should use:  \n-\t`ach` - Automated Clearing House (ACH) details\n-\t`pad` - Pre-authorized debit (PAD) details",
        ),
    ]
    payment: typing.Optional[PaymentSummary] = None
    transaction_result: typing_extensions.Annotated[
        BankTransferResult, FieldMetadata(alias="transactionResult"), pydantic.Field(alias="transactionResult")
    ]
    custom_fields: typing_extensions.Annotated[
        typing.Optional[typing.List[CustomField]],
        FieldMetadata(alias="customFields"),
        pydantic.Field(alias="customFields", description="Array of customField objects."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
