# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link
from .merchant_summary import MerchantSummary


class Batch(UniversalBaseModel):
    batch_id: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="batchId")] = pydantic.Field(
        default=None
    )
    """
    Unique identifier that we assigned to the batch.
    """

    date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Date that the merchant submitted the batch. The format of this value is **YYYY-MM-DD**.
    """

    created_date: typing_extensions.Annotated[typing.Optional[dt.date], FieldMetadata(alias="createdDate")] = (
        pydantic.Field(default=None)
    )
    """
    Date that we created a record for the batch. The format of this value is **YYYY-MM-DD**.
    """

    last_modified_date: typing_extensions.Annotated[
        typing.Optional[dt.date], FieldMetadata(alias="lastModifiedDate")
    ] = pydantic.Field(default=None)
    """
    Date that the batch was last changed. The format of this value is **YYYY-MM-DD**.
    """

    sale_amount: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="saleAmount")] = pydantic.Field(
        default=None
    )
    """
    Total value of sales in the batch. We return the value in the currency's lowest denomination, for example, cents.
    """

    held_amount: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="heldAmount")] = pydantic.Field(
        default=None
    )
    """
    Total value of authorizations in the batch. We return the value in the currency's lowest denomination, for example, cents.
    """

    return_amount: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="returnAmount")] = (
        pydantic.Field(default=None)
    )
    """
    Total value of returns in the batch. We return the value in the currency's lowest denomination, for example, cents.
    """

    transaction_count: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="transactionCount")] = (
        pydantic.Field(default=None)
    )
    """
    Total number of transactions in the batch.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency of the transactions in the batch. The value for the currency follows the [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) standard.
    """

    merchant: typing.Optional[MerchantSummary] = None
    links: typing.Optional[typing.List[Link]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
