# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .device import Device
from .ebt_details_with_voucher import EbtDetailsWithVoucher
from .encryption_capable_device import EncryptionCapableDevice
from .icc_card_details_downgrade_to import IccCardDetailsDowngradeTo
from .keyed_card_details_keyed_data import KeyedCardDetailsKeyedData
from .keyed_card_details_pin_details import KeyedCardDetailsPinDetails
from .raw_card_details_downgrade_to import RawCardDetailsDowngradeTo
from .swiped_card_details_downgrade_to import SwipedCardDetailsDowngradeTo
from .swiped_card_details_pin_details import SwipedCardDetailsPinDetails
from .swiped_card_details_swiped_data import SwipedCardDetailsSwipedData


class CardPayloadCardDetails_Raw(UniversalBaseModel):
    """
    Object that contains the details of the payment card.
    """

    entry_method: typing_extensions.Annotated[typing.Literal["raw"], FieldMetadata(alias="entryMethod")] = "raw"
    downgrade_to: typing_extensions.Annotated[
        typing.Optional[RawCardDetailsDowngradeTo], FieldMetadata(alias="downgradeTo")
    ] = None
    device: Device
    raw_data: typing_extensions.Annotated[str, FieldMetadata(alias="rawData")]
    cardholder_signature: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="cardholderSignature")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CardPayloadCardDetails_Icc(UniversalBaseModel):
    """
    Object that contains the details of the payment card.
    """

    entry_method: typing_extensions.Annotated[typing.Literal["icc"], FieldMetadata(alias="entryMethod")] = "icc"
    downgrade_to: typing_extensions.Annotated[
        typing.Optional[IccCardDetailsDowngradeTo], FieldMetadata(alias="downgradeTo")
    ] = None
    device: EncryptionCapableDevice
    icc_data: typing_extensions.Annotated[str, FieldMetadata(alias="iccData")]
    first_digit_of_pan: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="firstDigitOfPan")] = None
    cardholder_signature: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="cardholderSignature")
    ] = None
    ebt_details: typing_extensions.Annotated[
        typing.Optional[EbtDetailsWithVoucher], FieldMetadata(alias="ebtDetails")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CardPayloadCardDetails_Keyed(UniversalBaseModel):
    """
    Object that contains the details of the payment card.
    """

    entry_method: typing_extensions.Annotated[typing.Literal["keyed"], FieldMetadata(alias="entryMethod")] = "keyed"
    keyed_data: typing_extensions.Annotated[KeyedCardDetailsKeyedData, FieldMetadata(alias="keyedData")]
    cardholder_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="cardholderName")] = None
    cardholder_signature: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="cardholderSignature")
    ] = None
    pin_details: typing_extensions.Annotated[
        typing.Optional[KeyedCardDetailsPinDetails], FieldMetadata(alias="pinDetails")
    ] = None
    ebt_details: typing_extensions.Annotated[
        typing.Optional[EbtDetailsWithVoucher], FieldMetadata(alias="ebtDetails")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CardPayloadCardDetails_Swiped(UniversalBaseModel):
    """
    Object that contains the details of the payment card.
    """

    entry_method: typing_extensions.Annotated[typing.Literal["swiped"], FieldMetadata(alias="entryMethod")] = "swiped"
    downgrade_to: typing_extensions.Annotated[
        typing.Optional[SwipedCardDetailsDowngradeTo], FieldMetadata(alias="downgradeTo")
    ] = None
    swiped_data: typing_extensions.Annotated[SwipedCardDetailsSwipedData, FieldMetadata(alias="swipedData")]
    cardholder_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="cardholderName")] = None
    cardholder_signature: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="cardholderSignature")
    ] = None
    pin_details: typing_extensions.Annotated[
        typing.Optional[SwipedCardDetailsPinDetails], FieldMetadata(alias="pinDetails")
    ] = None
    ebt_details: typing_extensions.Annotated[
        typing.Optional[EbtDetailsWithVoucher], FieldMetadata(alias="ebtDetails")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CardPayloadCardDetails = typing_extensions.Annotated[
    typing.Union[
        CardPayloadCardDetails_Raw,
        CardPayloadCardDetails_Icc,
        CardPayloadCardDetails_Keyed,
        CardPayloadCardDetails_Swiped,
    ],
    pydantic.Field(discriminator="entry_method"),
]
