# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .consumer_choice_fees import ConsumerChoiceFees


class ConsumerChoice(UniversalBaseModel):
    """
    Object that contains information about ConsumerChoice.
    """

    fees: ConsumerChoiceFees = pydantic.Field()
    """
    Object that contains information about the fees.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
