# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ConvenienceFee(UniversalBaseModel):
    """
    Object that contains information about the convenience fee for the transaction.
    """

    amount: int = pydantic.Field()
    """
    If the merchant added a convenience fee, this value indicates the amount of the convenience fee
    in the currency’s lowest denomination, for example, cents.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
