# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .instruction_merchants_item import InstructionMerchantsItem
from .instruction_status import InstructionStatus


class Instruction(UniversalBaseModel):
    """
    Inform the payfac what to do with the specified funds. **
    """

    instruction_id: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="instructionId")] = (
        pydantic.Field(default=None)
    )
    """
    Unique identifier that we assigned to the funding instruction.
    """

    created_date: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="createdDate")] = (
        pydantic.Field(default=None)
    )
    """
    Date that we created the funding instruction. The date format follows the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard.
    """

    last_modified_date: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastModifiedDate")] = (
        pydantic.Field(default=None)
    )
    """
    Date of the most recent change to the funding instruction. The date format follows the [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard.
    """

    status: typing.Optional[InstructionStatus] = pydantic.Field(default=None)
    """
    Status of the funding instruction. Our gateway returns one of the following values:  
    - `accepted` - We have received the funding instruction but have not yet reviewed it.  
    - `pending` - We have received the funding instruction and we are reviewing it.  
    - `completed` - We have reviewed and processed the funding instruction.  
    """

    merchants: typing.Optional[typing.List[InstructionMerchantsItem]] = pydantic.Field(default=None)
    """
    Array of merchants objects. Each object specifies the merchant whose funding balance we distribute and who you want to send the funds to.
    """

    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    [Metadata](https://docs.payroc.com/api/metadata) object you can use to include custom data with your request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
