# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .amount import Amount
from .processor_fee import ProcessorFee


class InterchangePlusPlusFeesAmex_OptBlue(UniversalBaseModel):
    """
    Polymorphic object that contains fees for American Express transactions.

    The value of the type field determines which variant you should use:
    -    `optBlue` - Amex OptBlue pricing program.
    -    `direct` - Amex Direct pricing program.
    """

    type: typing.Literal["optBlue"] = "optBlue"
    qualified_rate: typing_extensions.Annotated[
        ProcessorFee, FieldMetadata(alias="qualifiedRate"), pydantic.Field(alias="qualifiedRate")
    ]
    mid_qual_rate: typing_extensions.Annotated[
        ProcessorFee, FieldMetadata(alias="midQualRate"), pydantic.Field(alias="midQualRate")
    ]
    non_qual_rate: typing_extensions.Annotated[
        ProcessorFee, FieldMetadata(alias="nonQualRate"), pydantic.Field(alias="nonQualRate")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class InterchangePlusPlusFeesAmex_Direct(UniversalBaseModel):
    """
    Polymorphic object that contains fees for American Express transactions.

    The value of the type field determines which variant you should use:
    -    `optBlue` - Amex OptBlue pricing program.
    -    `direct` - Amex Direct pricing program.
    """

    type: typing.Literal["direct"] = "direct"
    transaction: Amount

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


InterchangePlusPlusFeesAmex = typing_extensions.Annotated[
    typing.Union[InterchangePlusPlusFeesAmex_OptBlue, InterchangePlusPlusFeesAmex_Direct],
    pydantic.Field(discriminator="type"),
]
