# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .business import Business
from .link import Link
from .merchant_platform_processing_accounts_item import MerchantPlatformProcessingAccountsItem


class MerchantPlatform(UniversalBaseModel):
    merchant_platform_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="merchantPlatformId")
    ] = pydantic.Field(default=None)
    """
    Unique identifier that we assigned to the merchant platform.
    """

    created_date: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdDate")] = (
        pydantic.Field(default=None)
    )
    """
    Date that the merchant platform was created. We return this value in the [ISO-8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
    """

    last_modified_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastModifiedDate")
    ] = pydantic.Field(default=None)
    """
    Date that the merchant platform was last modified. We return this value in the [ISO-8601](https://www.iso.org/iso-8601-date-and-time-format.html) format.
    """

    business: Business
    processing_accounts: typing_extensions.Annotated[
        typing.Optional[typing.List[MerchantPlatformProcessingAccountsItem]], FieldMetadata(alias="processingAccounts")
    ] = pydantic.Field(default=None)
    """
    Array of processingAccount objects.
    """

    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Object that you can send to include custom metadata in the request.
    """

    links: typing.Optional[typing.List[Link]] = pydantic.Field(default=None)
    """
    Array of useful links related to your request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
