# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class MerchantBalance(UniversalBaseModel):
    """
    Object that contains information about the total funds available to the merchant.
    """

    merchant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="merchantId"),
        pydantic.Field(
            alias="merchantId", description="Unique identifier that the processor assigned to the merchant."
        ),
    ] = None
    funds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total funding balance for the merchant, including pending amounts. The value is in the currency's lowest denomination, for example, cents.
    """

    pending: typing.Optional[int] = pydantic.Field(default=None)
    """
    Amount of the funding balance that we have not yet sent to funding accounts. The value is in the currency's lowest denomination, for example, cents.
    """

    available: typing.Optional[int] = pydantic.Field(default=None)
    """
    Amount of the funding balance that you can use in funding instructions. The value is in the currency's lowest denomination, for example, cents.
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency of the funding balance. We return a value of `USD`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
