# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .multi_use_payment_link_order_charge import MultiUsePaymentLinkOrderCharge


class MultiUsePaymentLinkOrder(UniversalBaseModel):
    """
    Object that contains information about the order.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A brief description of the transaction.
    """

    charge: MultiUsePaymentLinkOrderCharge = pydantic.Field()
    """
    Polymorphic object that indicates who enters the amount for the payment link.  
    
    The value of the type parameter determines which variant you should use:  
    -    `prompt` - Customer enters the amount.
    -    `preset` - Merchant sets the amount. 
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
