# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .offline_processing_operation import OfflineProcessingOperation


class OfflineProcessing(UniversalBaseModel):
    """
    Object that contains information about the transaction if the merchant ran it when the terminal was offline.
    """

    operation: OfflineProcessingOperation = pydantic.Field()
    """
    Status of the transaction.
    """

    approval_code: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="approvalCode")] = (
        pydantic.Field(default=None)
    )
    """
    Approval code for the transaction from the processor.
    """

    date_time: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="dateTime")] = (
        pydantic.Field(default=None)
    )
    """
    Date and time that the merchant ran the transaction. The date follows the ISO 8601 standard.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
