# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class OrderItemSolutionSetupApplicationSettingsSecurity(UniversalBaseModel):
    """
    Object that contains the password settings when running specific transaction types.
    """

    refund_password: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="refundPassword")] = (
        pydantic.Field(default=None)
    )
    """
    Indicates if the terminal should prompt the clerk for a password when running a refund.
    """

    keyed_sale_password: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="keyedSalePassword")
    ] = pydantic.Field(default=None)
    """
    Indicates if the terminal should prompt the clerk for a password when running a keyed sale.
    """

    reversal_password: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="reversalPassword")] = (
        pydantic.Field(default=None)
    )
    """
    Indicates if the terminal should prompt the clerk for a password when cancelling a transaction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
