# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .event_subscription import EventSubscription
from .paginated_list import PaginatedList


class PaginatedEventSubscriptions(PaginatedList):
    data: typing.Optional[typing.List[EventSubscription]] = pydantic.Field(default=None)
    """
    Array of eventSubscription objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
