# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .funding_recipient import FundingRecipient
from .paginated_list import PaginatedList


class PaginatedFundRecipients(PaginatedList):
    data: typing.Optional[typing.List[FundingRecipient]] = pydantic.Field(default=None)
    """
    An array of funding recipients
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
