# This file was auto-generated by Fern from our API Definition.

import typing

PaymentPlanBaseFrequency = typing.Union[
    typing.Literal["weekly", "fortnightly", "monthly", "quarterly", "yearly"], typing.Any
]
