# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class PaymentPlanSummary(UniversalBaseModel):
    payment_plan_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="paymentPlanId"),
        pydantic.Field(
            alias="paymentPlanId", description="Unique identifier that the merchant assigns to the payment plan."
        ),
    ]
    name: str = pydantic.Field()
    """
    Name of the payment plan.
    """

    link: typing.Optional[Link] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
