# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .device import Device


class PlainTextKeyedDataFormat(UniversalBaseModel):
    """
    Object that contains information about the plain-text card data for keyed transactions.
    """

    device: typing.Optional[Device] = None
    card_number: typing_extensions.Annotated[str, FieldMetadata(alias="cardNumber")] = pydantic.Field()
    """
    Customer’s card number.
    """

    expiry_date: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="expiryDate")] = pydantic.Field(
        default=None
    )
    """
    Expiry date of the customer’s card.  
    **Note:** We require you to send an expiry date for most BIN lookups and electronic voucher transactions.
    """

    cvv: typing.Optional[str] = pydantic.Field(default=None)
    """
    Security code of the customer’s card.
    """

    issue_number: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="issueNumber")] = (
        pydantic.Field(default=None)
    )
    """
    Issue number of the customer’s card.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
