# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Pricing_Intent(UniversalBaseModel):
    """
    Polymorphic object that contains pricing information for the processing account.

    The value of the type parameter determines which variant you should use:
    -    `intent` - Use a pricing agreement template.
    -    `agreement` - Create a new pricing agreement.
    """

    type: typing.Literal["intent"] = "intent"
    pricing_intent_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="pricingIntentId"), pydantic.Field(alias="pricingIntentId")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Pricing_Agreement(UniversalBaseModel):
    """
    Polymorphic object that contains pricing information for the processing account.

    The value of the type parameter determines which variant you should use:
    -    `intent` - Use a pricing agreement template.
    -    `agreement` - Create a new pricing agreement.
    """

    type: typing.Literal["agreement"] = "agreement"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Pricing = typing_extensions.Annotated[
    typing.Union[Pricing_Intent, Pricing_Agreement], pydantic.Field(discriminator="type")
]
