# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ProcessingCardAcceptanceSpecialityCardsOther(UniversalBaseModel):
    """
    Object that contains information about other speciality cards that the merchant accepts.
    """

    wex_merchant_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="wexMerchantNumber"),
        pydantic.Field(
            alias="wexMerchantNumber", description="If the merchant accepts WEX, provide their WEX merchant number."
        ),
    ] = None
    voyager_merchant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="voyagerMerchantId"),
        pydantic.Field(
            alias="voyagerMerchantId", description="If the merchant accepts Voyager, provide their Voyager merchant ID."
        ),
    ] = None
    fleet_merchant_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="fleetMerchantId"),
        pydantic.Field(
            alias="fleetMerchantId", description="If the merchant accepts Fleet, provide their Fleet merchant ID."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
