# This file was auto-generated by Fern from our API Definition.

import typing

ProcessingAccountStatus = typing.Union[
    typing.Literal[
        "entered", "pending", "approved", "subjectTo", "dormant", "nonProcessing", "rejected", "terminated", "cancelled"
    ],
    typing.Any,
]
