# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProcessingAccountOwnersItemLink(UniversalBaseModel):
    """
    HATEOAS links to the owners of the processing account.
    """

    rel: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indicates the relationship between the current resource and the target resource.
    """

    href: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the target resource.
    """

    method: typing.Optional[str] = pydantic.Field(default=None)
    """
    HTTP method that you need to use with the target resource.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
