# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .processing_terminal_features_ebt import ProcessingTerminalFeaturesEbt
from .processing_terminal_features_enhanced_processing import ProcessingTerminalFeaturesEnhancedProcessing
from .processing_terminal_features_payment_links import ProcessingTerminalFeaturesPaymentLinks
from .processing_terminal_features_tips import ProcessingTerminalFeaturesTips


class ProcessingTerminalFeatures(UniversalBaseModel):
    """
    Object that contains the feature settings for the terminal.
    """

    tips: typing.Optional[ProcessingTerminalFeaturesTips] = pydantic.Field(default=None)
    """
    Object that contains the tip settings for the processing terminal.
    """

    enhanced_processing: typing_extensions.Annotated[
        ProcessingTerminalFeaturesEnhancedProcessing, FieldMetadata(alias="enhancedProcessing")
    ] = pydantic.Field()
    """
    Object that contains details about level two and level three transactions.
    """

    ebt: ProcessingTerminalFeaturesEbt = pydantic.Field()
    """
    Object that contains details about EBT transactions.
    """

    pin_debit_cashback: typing_extensions.Annotated[bool, FieldMetadata(alias="pinDebitCashback")] = pydantic.Field()
    """
    Indicates if the terminal prompts for cashback on PIN debit transactions.
    """

    recurring_payments: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="recurringPayments")] = (
        pydantic.Field(default=None)
    )
    """
    Indicates if the terminal can run repeat payments. For more information about repeat payments, go to [Payment Plans](https://docs.payroc.com/guides/integrate/repeat-payments).
    """

    payment_links: typing_extensions.Annotated[
        typing.Optional[ProcessingTerminalFeaturesPaymentLinks], FieldMetadata(alias="paymentLinks")
    ] = pydantic.Field(default=None)
    """
    Object that contains details about payment links.
    """

    pre_authorizations: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="preAuthorizations")] = (
        pydantic.Field(default=None)
    )
    """
    Indicates if the terminal can run pre-authorizations.
    """

    offline_payments: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="offlinePayments")] = (
        pydantic.Field(default=None)
    )
    """
    Indicates if the terminal can accept payments when it can't connect to the gateway. For more information about offline processing, go to [Offline Processing](https://docs.payroc.com/knowledge/card-payments/offline-processing).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
