# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .processing_account_pricing_link import ProcessingAccountPricingLink


class ProcessingAccountPricing(UniversalBaseModel):
    """
    Object that HATEOAS links to the pricing information that we apply to the processing account.
    """

    link: typing.Optional[ProcessingAccountPricingLink] = pydantic.Field(default=None)
    """
    Object that contains HATEOAS links to the pricing information for the processing account.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
