# This file was auto-generated by Fern from our API Definition.

import typing

ProcessingTerminalFeaturesEnhancedProcessingShippingAddressMode = typing.Union[
    typing.Literal["fullAddress", "postalCode"], typing.Any
]
