# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .processing_terminal_security_avs_level import ProcessingTerminalSecurityAvsLevel


class ProcessingTerminalSecurity(UniversalBaseModel):
    """
    Object that contains the tokenization settings and AVS settings for the terminal.
    """

    tokenization: bool = pydantic.Field()
    """
    Indicates if the terminal can tokenize customer's payment details. For more information about tokenization, go to [Tokenization](https://docs.payroc.com/knowledge/basic-concepts/tokenization).
    """

    avs_prompt: typing_extensions.Annotated[bool, FieldMetadata(alias="avsPrompt")] = pydantic.Field()
    """
    Indicates if the terminal should prompt for Address Verification Service (AVS) details when running a transaction.
    """

    avs_level: typing_extensions.Annotated[
        typing.Optional[ProcessingTerminalSecurityAvsLevel], FieldMetadata(alias="avsLevel")
    ] = pydantic.Field(default=None)
    """
    Indicates the level of AVS details that the terminal should prompt for.
    """

    cvv_prompt: typing_extensions.Annotated[bool, FieldMetadata(alias="cvvPrompt")] = pydantic.Field()
    """
    Indicates if the terminal should prompt for a Card Verfication Value (CVV) when running a transaction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
