# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ProcessingTerminalTaxesItem(UniversalBaseModel):
    """
    Object that contains a tax rate with a short description of the tax rate.
    """

    tax_rate: typing_extensions.Annotated[float, FieldMetadata(alias="taxRate")] = pydantic.Field()
    """
    Rate of tax that the terminal applies to each transaction.
    """

    tax_label: typing_extensions.Annotated[str, FieldMetadata(alias="taxLabel")] = pydantic.Field()
    """
    Short description of the tax rate, for example, "Sales Tax".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
