# This file was auto-generated by Fern from our API Definition.

import typing

ProcessingAccountBusinessType = typing.Union[
    typing.Literal["retail", "restaurant", "internet", "moto", "lodging", "notForProfit"], typing.Any
]
