# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .amount import Amount
from .percentage import Percentage


class ProcessorFee(UniversalBaseModel):
    """
    Object that contains information about the processor fees.
    """

    volume: typing.Optional[Percentage] = pydantic.Field(default=None)
    """
    Percentage of total transaction amount that the processor charges the merchant.
    """

    transaction: typing.Optional[Amount] = pydantic.Field(default=None)
    """
    Fee for each transaction. The value is in the currency's lowest denomination, for example, cents.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
