# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .processor_fee import ProcessorFee
from .qual_rates_with_premium import QualRatesWithPremium


class QualRatesWithPremiumAndRegulated(QualRatesWithPremium):
    regulated_check_card: typing_extensions.Annotated[ProcessorFee, FieldMetadata(alias="regulatedCheckCard")] = (
        pydantic.Field()
    )
    """
    Object that contains the fees for a regulated debit-card transaction.
    """

    unregulated_check_card: typing_extensions.Annotated[ProcessorFee, FieldMetadata(alias="unregulatedCheckCard")] = (
        pydantic.Field()
    )
    """
    Object that contains the fees for an unregulated debit-card transaction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
