# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .contact_method import ContactMethod
from .retrieved_address import RetrievedAddress
from .retrieved_customer_notification_language import RetrievedCustomerNotificationLanguage
from .retrieved_shipping import RetrievedShipping


class RetrievedCustomer(UniversalBaseModel):
    """
    Object that contains the customer's contact details and address information.
    """

    first_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="firstName")] = pydantic.Field(
        default=None
    )
    """
    Customer's first name.
    """

    last_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="lastName")] = pydantic.Field(
        default=None
    )
    """
    Customer's last name.
    """

    date_of_birth: typing_extensions.Annotated[typing.Optional[dt.date], FieldMetadata(alias="dateOfBirth")] = (
        pydantic.Field(default=None)
    )
    """
    Customer's date of birth. The format for this value is **YYYY-MM-DD**.
    """

    reference_number: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="referenceNumber")] = (
        pydantic.Field(default=None)
    )
    """
    Identifier of the transaction, also known as a customer code. 
    
    For requests, you must send a value for **referenceNumber** if the customer provides one. 
    """

    billing_address: typing_extensions.Annotated[
        typing.Optional[RetrievedAddress], FieldMetadata(alias="billingAddress")
    ] = pydantic.Field(default=None)
    """
    Object that contains information about the address that the card is registered to.
    """

    shipping_address: typing_extensions.Annotated[
        typing.Optional[RetrievedShipping], FieldMetadata(alias="shippingAddress")
    ] = None
    contact_methods: typing_extensions.Annotated[
        typing.Optional[typing.List[ContactMethod]], FieldMetadata(alias="contactMethods")
    ] = pydantic.Field(default=None)
    """
    Customer's contact information.
    """

    notification_language: typing_extensions.Annotated[
        typing.Optional[RetrievedCustomerNotificationLanguage], FieldMetadata(alias="notificationLanguage")
    ] = pydantic.Field(default=None)
    """
    Language that the customer uses for notifications. This code follows the [ISO 639-1](https://www.iso.org/iso-639-language-code) alpha-2 standard. 
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
