# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .amount import Amount
from .reward_pay_fees_tips import RewardPayFeesTips
from .speciality_cards import SpecialityCards


class RewardPayFees(UniversalBaseModel):
    """
    Object that contains information about the fees.
    """

    monthly_subscription: typing_extensions.Annotated[
        Amount,
        FieldMetadata(alias="monthlySubscription"),
        pydantic.Field(
            alias="monthlySubscription",
            description="Fee for the monthly subscription for the processing plan. The value is in the currency's lowest denomination, for example, cents.",
        ),
    ]
    card_charge_percentage: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="cardChargePercentage"),
        pydantic.Field(
            alias="cardChargePercentage",
            description="Percentage of the total transaction amount that the processor charges the cardholder.",
        ),
    ] = None
    merchant_charge_percentage: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="merchantChargePercentage"),
        pydantic.Field(
            alias="merchantChargePercentage",
            description="Percentage of the total transaction amount that the processor charges the merchant.",
        ),
    ] = None
    transaction: typing.Optional[int] = pydantic.Field(default=None)
    """
    Fee for each transaction. The value is in the currency's lowest denomination, for example, cents.
    """

    tips: RewardPayFeesTips = pydantic.Field()
    """
    Indicates how the merchant manages tips.
    """

    speciality_cards: typing_extensions.Annotated[
        typing.Optional[SpecialityCards],
        FieldMetadata(alias="specialityCards"),
        pydantic.Field(alias="specialityCards"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
