# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .secure_token_payload_account_type import SecureTokenPayloadAccountType
from .secure_token_payload_sec_code import SecureTokenPayloadSecCode


class SecureTokenPayload(UniversalBaseModel):
    """
    Object that contains information about the secure token that represents the customer’s payment details.
    """

    account_type: typing_extensions.Annotated[
        typing.Optional[SecureTokenPayloadAccountType], FieldMetadata(alias="accountType")
    ] = pydantic.Field(default=None)
    """
    Indicates the customer’s account type.  
    
    **Note:** Send a value for accountType only if the secure token represents bank account details.
    """

    token: str = pydantic.Field()
    """
    Unique token that the gateway assigned to the payment details.
    """

    sec_code: typing_extensions.Annotated[
        typing.Optional[SecureTokenPayloadSecCode], FieldMetadata(alias="secCode")
    ] = pydantic.Field(default=None)
    """
    Indicates how the customer authorized the ACH transaction. Send one of the following values:  
    
    - `web` – Online transaction.  
    - `tel` – Telephone transaction.  
    - `ccd` – Corporate credit card or debit card transaction.  
    - `ppd` – Pre-arranged transaction. 
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
