# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tax_rate_type import TaxRateType


class Tax_Amount(UniversalBaseModel):
    """
    Object that contains information about the tax details.
    """

    type: typing.Literal["amount"] = "amount"
    amount: int
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class Tax_Rate(UniversalBaseModel):
    """
    Object that contains information about the tax details.
    """

    type: typing.Literal["rate"] = "rate"
    rate: float
    name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


Tax = typing_extensions.Annotated[typing.Union[Tax_Amount, Tax_Rate], pydantic.Field(discriminator="type")]
