# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tax_rate_type import TaxRateType


class TaxRate(UniversalBaseModel):
    type: TaxRateType = pydantic.Field()
    """
    Indicates that the tax is a rate.
    """

    rate: float = pydantic.Field()
    """
    Tax percentage for the transaction.
    """

    name: str = pydantic.Field()
    """
    Name of the tax. A tax validation on the stored rate for the tax name is performed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
