# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .bank_transfer_payment_request_payment_method import (
        BankTransferPaymentRequestPaymentMethod,
        BankTransferPaymentRequestPaymentMethod_Ach,
        BankTransferPaymentRequestPaymentMethod_Pad,
        BankTransferPaymentRequestPaymentMethod_SecureToken,
        BankTransferPaymentRequestPaymentMethod_SingleUseToken,
    )
    from .list_payments_request_settlement_state import ListPaymentsRequestSettlementState
    from .list_payments_request_status_item import ListPaymentsRequestStatusItem
    from .list_payments_request_type_item import ListPaymentsRequestTypeItem
    from .representment_payment_method import (
        RepresentmentPaymentMethod,
        RepresentmentPaymentMethod_Ach,
        RepresentmentPaymentMethod_SecureToken,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "BankTransferPaymentRequestPaymentMethod": ".bank_transfer_payment_request_payment_method",
    "BankTransferPaymentRequestPaymentMethod_Ach": ".bank_transfer_payment_request_payment_method",
    "BankTransferPaymentRequestPaymentMethod_Pad": ".bank_transfer_payment_request_payment_method",
    "BankTransferPaymentRequestPaymentMethod_SecureToken": ".bank_transfer_payment_request_payment_method",
    "BankTransferPaymentRequestPaymentMethod_SingleUseToken": ".bank_transfer_payment_request_payment_method",
    "ListPaymentsRequestSettlementState": ".list_payments_request_settlement_state",
    "ListPaymentsRequestStatusItem": ".list_payments_request_status_item",
    "ListPaymentsRequestTypeItem": ".list_payments_request_type_item",
    "RepresentmentPaymentMethod": ".representment_payment_method",
    "RepresentmentPaymentMethod_Ach": ".representment_payment_method",
    "RepresentmentPaymentMethod_SecureToken": ".representment_payment_method",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BankTransferPaymentRequestPaymentMethod",
    "BankTransferPaymentRequestPaymentMethod_Ach",
    "BankTransferPaymentRequestPaymentMethod_Pad",
    "BankTransferPaymentRequestPaymentMethod_SecureToken",
    "BankTransferPaymentRequestPaymentMethod_SingleUseToken",
    "ListPaymentsRequestSettlementState",
    "ListPaymentsRequestStatusItem",
    "ListPaymentsRequestTypeItem",
    "RepresentmentPaymentMethod",
    "RepresentmentPaymentMethod_Ach",
    "RepresentmentPaymentMethod_SecureToken",
]
