# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from ....types.ach_payload_account_type import AchPayloadAccountType
from ....types.ach_payload_sec_code import AchPayloadSecCode
from ....types.ebt_details_with_voucher import EbtDetailsWithVoucher
from ....types.pad_payload_account_type import PadPayloadAccountType
from ....types.secure_token_payload_account_type import SecureTokenPayloadAccountType
from ....types.secure_token_payload_sec_code import SecureTokenPayloadSecCode
from ....types.single_use_token_payload_account_type import SingleUseTokenPayloadAccountType
from ....types.single_use_token_payload_pin_details import SingleUseTokenPayloadPinDetails
from ....types.single_use_token_payload_sec_code import SingleUseTokenPayloadSecCode


class BankTransferPaymentRequestPaymentMethod_Ach(UniversalBaseModel):
    """
    Polymorphic object that contains payment detail information.

    The value of the type parameter determines which variant you should use:
    -    `ach` - Automated Clearing House (ACH) details
    -    `pad` - Pre-authorized debit (PAD) details
    -    `secureToken` - Secure token details
    -    `singleUseToken` - Single-use token details
    """

    type: typing.Literal["ach"] = "ach"
    account_type: typing_extensions.Annotated[
        typing.Optional[AchPayloadAccountType], FieldMetadata(alias="accountType"), pydantic.Field(alias="accountType")
    ] = None
    sec_code: typing_extensions.Annotated[
        typing.Optional[AchPayloadSecCode], FieldMetadata(alias="secCode"), pydantic.Field(alias="secCode")
    ] = None
    name_on_account: typing_extensions.Annotated[
        str, FieldMetadata(alias="nameOnAccount"), pydantic.Field(alias="nameOnAccount")
    ]
    account_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="accountNumber"), pydantic.Field(alias="accountNumber")
    ]
    routing_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="routingNumber"), pydantic.Field(alias="routingNumber")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BankTransferPaymentRequestPaymentMethod_Pad(UniversalBaseModel):
    """
    Polymorphic object that contains payment detail information.

    The value of the type parameter determines which variant you should use:
    -    `ach` - Automated Clearing House (ACH) details
    -    `pad` - Pre-authorized debit (PAD) details
    -    `secureToken` - Secure token details
    -    `singleUseToken` - Single-use token details
    """

    type: typing.Literal["pad"] = "pad"
    account_type: typing_extensions.Annotated[
        typing.Optional[PadPayloadAccountType], FieldMetadata(alias="accountType"), pydantic.Field(alias="accountType")
    ] = None
    name_on_account: typing_extensions.Annotated[
        str, FieldMetadata(alias="nameOnAccount"), pydantic.Field(alias="nameOnAccount")
    ]
    account_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="accountNumber"), pydantic.Field(alias="accountNumber")
    ]
    transit_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="transitNumber"), pydantic.Field(alias="transitNumber")
    ]
    institution_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="institutionNumber"), pydantic.Field(alias="institutionNumber")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BankTransferPaymentRequestPaymentMethod_SecureToken(UniversalBaseModel):
    """
    Polymorphic object that contains payment detail information.

    The value of the type parameter determines which variant you should use:
    -    `ach` - Automated Clearing House (ACH) details
    -    `pad` - Pre-authorized debit (PAD) details
    -    `secureToken` - Secure token details
    -    `singleUseToken` - Single-use token details
    """

    type: typing.Literal["secureToken"] = "secureToken"
    account_type: typing_extensions.Annotated[
        typing.Optional[SecureTokenPayloadAccountType],
        FieldMetadata(alias="accountType"),
        pydantic.Field(alias="accountType"),
    ] = None
    token: str
    sec_code: typing_extensions.Annotated[
        typing.Optional[SecureTokenPayloadSecCode], FieldMetadata(alias="secCode"), pydantic.Field(alias="secCode")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BankTransferPaymentRequestPaymentMethod_SingleUseToken(UniversalBaseModel):
    """
    Polymorphic object that contains payment detail information.

    The value of the type parameter determines which variant you should use:
    -    `ach` - Automated Clearing House (ACH) details
    -    `pad` - Pre-authorized debit (PAD) details
    -    `secureToken` - Secure token details
    -    `singleUseToken` - Single-use token details
    """

    type: typing.Literal["singleUseToken"] = "singleUseToken"
    account_type: typing_extensions.Annotated[
        typing.Optional[SingleUseTokenPayloadAccountType],
        FieldMetadata(alias="accountType"),
        pydantic.Field(alias="accountType"),
    ] = None
    token: str
    pin_details: typing_extensions.Annotated[
        typing.Optional[SingleUseTokenPayloadPinDetails],
        FieldMetadata(alias="pinDetails"),
        pydantic.Field(alias="pinDetails"),
    ] = None
    ebt_details: typing_extensions.Annotated[
        typing.Optional[EbtDetailsWithVoucher], FieldMetadata(alias="ebtDetails"), pydantic.Field(alias="ebtDetails")
    ] = None
    sec_code: typing_extensions.Annotated[
        typing.Optional[SingleUseTokenPayloadSecCode], FieldMetadata(alias="secCode"), pydantic.Field(alias="secCode")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


BankTransferPaymentRequestPaymentMethod = typing_extensions.Annotated[
    typing.Union[
        BankTransferPaymentRequestPaymentMethod_Ach,
        BankTransferPaymentRequestPaymentMethod_Pad,
        BankTransferPaymentRequestPaymentMethod_SecureToken,
        BankTransferPaymentRequestPaymentMethod_SingleUseToken,
    ],
    pydantic.Field(discriminator="type"),
]
