# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawBankTransferPaymentsClient, RawBankTransferPaymentsClient

if typing.TYPE_CHECKING:
    from .payments.client import AsyncPaymentsClient, PaymentsClient
    from .refunds.client import AsyncRefundsClient, RefundsClient


class BankTransferPaymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBankTransferPaymentsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._payments: typing.Optional[PaymentsClient] = None
        self._refunds: typing.Optional[RefundsClient] = None

    @property
    def with_raw_response(self) -> RawBankTransferPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBankTransferPaymentsClient
        """
        return self._raw_client

    @property
    def payments(self):
        if self._payments is None:
            from .payments.client import PaymentsClient  # noqa: E402

            self._payments = PaymentsClient(client_wrapper=self._client_wrapper)
        return self._payments

    @property
    def refunds(self):
        if self._refunds is None:
            from .refunds.client import RefundsClient  # noqa: E402

            self._refunds = RefundsClient(client_wrapper=self._client_wrapper)
        return self._refunds


class AsyncBankTransferPaymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBankTransferPaymentsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._payments: typing.Optional[AsyncPaymentsClient] = None
        self._refunds: typing.Optional[AsyncRefundsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawBankTransferPaymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBankTransferPaymentsClient
        """
        return self._raw_client

    @property
    def payments(self):
        if self._payments is None:
            from .payments.client import AsyncPaymentsClient  # noqa: E402

            self._payments = AsyncPaymentsClient(client_wrapper=self._client_wrapper)
        return self._payments

    @property
    def refunds(self):
        if self._refunds is None:
            from .refunds.client import AsyncRefundsClient  # noqa: E402

            self._refunds = AsyncRefundsClient(client_wrapper=self._client_wrapper)
        return self._refunds
