# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from ....types.ach_payload_account_type import AchPayloadAccountType
from ....types.ach_payload_sec_code import AchPayloadSecCode
from ....types.secure_token_payload_account_type import SecureTokenPayloadAccountType
from ....types.secure_token_payload_sec_code import SecureTokenPayloadSecCode


class BankTransferUnreferencedRefundRefundMethod_Ach(UniversalBaseModel):
    """
    Object that contains information about how the merchant refunds the customer.
    """

    type: typing.Literal["ach"] = "ach"
    account_type: typing_extensions.Annotated[
        typing.Optional[AchPayloadAccountType], FieldMetadata(alias="accountType")
    ] = None
    sec_code: typing_extensions.Annotated[typing.Optional[AchPayloadSecCode], FieldMetadata(alias="secCode")] = None
    name_on_account: typing_extensions.Annotated[str, FieldMetadata(alias="nameOnAccount")]
    account_number: typing_extensions.Annotated[str, FieldMetadata(alias="accountNumber")]
    routing_number: typing_extensions.Annotated[str, FieldMetadata(alias="routingNumber")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BankTransferUnreferencedRefundRefundMethod_SecureToken(UniversalBaseModel):
    """
    Object that contains information about how the merchant refunds the customer.
    """

    type: typing.Literal["secureToken"] = "secureToken"
    account_type: typing_extensions.Annotated[
        typing.Optional[SecureTokenPayloadAccountType], FieldMetadata(alias="accountType")
    ] = None
    token: str
    sec_code: typing_extensions.Annotated[
        typing.Optional[SecureTokenPayloadSecCode], FieldMetadata(alias="secCode")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


BankTransferUnreferencedRefundRefundMethod = typing_extensions.Annotated[
    typing.Union[
        BankTransferUnreferencedRefundRefundMethod_Ach, BankTransferUnreferencedRefundRefundMethod_SecureToken
    ],
    pydantic.Field(discriminator="type"),
]
