# This file was auto-generated by Fern from our API Definition.

import typing

ListRefundsRequestStatusItem = typing.Union[
    typing.Literal["ready", "pending", "declined", "complete", "admin", "reversal", "returned"], typing.Any
]
