# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.four_hundred_four import FourHundredFour


class NotFoundError(ApiError):
    def __init__(self, body: FourHundredFour, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=404, headers=headers, body=body)
