# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawPaymentFeaturesClient, RawPaymentFeaturesClient

if typing.TYPE_CHECKING:
    from .bank.client import AsyncBankClient, BankClient
    from .cards.client import AsyncCardsClient, CardsClient


class PaymentFeaturesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPaymentFeaturesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._cards: typing.Optional[CardsClient] = None
        self._bank: typing.Optional[BankClient] = None

    @property
    def with_raw_response(self) -> RawPaymentFeaturesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPaymentFeaturesClient
        """
        return self._raw_client

    @property
    def cards(self):
        if self._cards is None:
            from .cards.client import CardsClient  # noqa: E402

            self._cards = CardsClient(client_wrapper=self._client_wrapper)
        return self._cards

    @property
    def bank(self):
        if self._bank is None:
            from .bank.client import BankClient  # noqa: E402

            self._bank = BankClient(client_wrapper=self._client_wrapper)
        return self._bank


class AsyncPaymentFeaturesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPaymentFeaturesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._cards: typing.Optional[AsyncCardsClient] = None
        self._bank: typing.Optional[AsyncBankClient] = None

    @property
    def with_raw_response(self) -> AsyncRawPaymentFeaturesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPaymentFeaturesClient
        """
        return self._raw_client

    @property
    def cards(self):
        if self._cards is None:
            from .cards.client import AsyncCardsClient  # noqa: E402

            self._cards = AsyncCardsClient(client_wrapper=self._client_wrapper)
        return self._cards

    @property
    def bank(self):
        if self._bank is None:
            from .bank.client import AsyncBankClient  # noqa: E402

            self._bank = AsyncBankClient(client_wrapper=self._client_wrapper)
        return self._bank
