# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .attachment_entity import AttachmentEntity
from .attachment_type import AttachmentType
from .attachment_upload_status import AttachmentUploadStatus


class Attachment(UniversalBaseModel):
    attachment_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="attachmentId"),
        pydantic.Field(
            alias="attachmentId", description="Unique identifier that our gateway assigned to the attachment."
        ),
    ]
    type: AttachmentType = pydantic.Field()
    """
    Type of attachment.
    """

    upload_status: typing_extensions.Annotated[
        AttachmentUploadStatus,
        FieldMetadata(alias="uploadStatus"),
        pydantic.Field(
            alias="uploadStatus",
            description="Upload status of the attachment. The value is one of the following:\n- `pending` - We have not yet uploaded the attachment.\n- `accepted` - We have uploaded the attachment. \n- `rejected` - We rejected the attachment. ",
        ),
    ]
    file_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="fileName"), pydantic.Field(alias="fileName", description="Name of the file.")
    ]
    content_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="contentType"),
        pydantic.Field(alias="contentType", description="Content type of the file."),
    ]
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short description of the attachment.
    """

    entity: AttachmentEntity = pydantic.Field()
    """
    Object that contains information about the entity that the attachment is linked to.
    """

    created_date: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdDate"),
        pydantic.Field(
            alias="createdDate", description="Date and time that we received your request to upload the attachment."
        ),
    ]
    last_modified_date: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="lastModifiedDate"),
        pydantic.Field(alias="lastModifiedDate", description="Date and time the attachment was last modified."),
    ]
    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Object that you can send to include custom metadata in the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
