# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawPayrocCloudClient, RawPayrocCloudClient

if typing.TYPE_CHECKING:
    from .payment_instructions.client import AsyncPaymentInstructionsClient, PaymentInstructionsClient
    from .refund_instructions.client import AsyncRefundInstructionsClient, RefundInstructionsClient
    from .signature_instructions.client import AsyncSignatureInstructionsClient, SignatureInstructionsClient
    from .signatures.client import AsyncSignaturesClient, SignaturesClient


class PayrocCloudClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPayrocCloudClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._payment_instructions: typing.Optional[PaymentInstructionsClient] = None
        self._refund_instructions: typing.Optional[RefundInstructionsClient] = None
        self._signature_instructions: typing.Optional[SignatureInstructionsClient] = None
        self._signatures: typing.Optional[SignaturesClient] = None

    @property
    def with_raw_response(self) -> RawPayrocCloudClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPayrocCloudClient
        """
        return self._raw_client

    @property
    def payment_instructions(self):
        if self._payment_instructions is None:
            from .payment_instructions.client import PaymentInstructionsClient  # noqa: E402

            self._payment_instructions = PaymentInstructionsClient(client_wrapper=self._client_wrapper)
        return self._payment_instructions

    @property
    def refund_instructions(self):
        if self._refund_instructions is None:
            from .refund_instructions.client import RefundInstructionsClient  # noqa: E402

            self._refund_instructions = RefundInstructionsClient(client_wrapper=self._client_wrapper)
        return self._refund_instructions

    @property
    def signature_instructions(self):
        if self._signature_instructions is None:
            from .signature_instructions.client import SignatureInstructionsClient  # noqa: E402

            self._signature_instructions = SignatureInstructionsClient(client_wrapper=self._client_wrapper)
        return self._signature_instructions

    @property
    def signatures(self):
        if self._signatures is None:
            from .signatures.client import SignaturesClient  # noqa: E402

            self._signatures = SignaturesClient(client_wrapper=self._client_wrapper)
        return self._signatures


class AsyncPayrocCloudClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPayrocCloudClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._payment_instructions: typing.Optional[AsyncPaymentInstructionsClient] = None
        self._refund_instructions: typing.Optional[AsyncRefundInstructionsClient] = None
        self._signature_instructions: typing.Optional[AsyncSignatureInstructionsClient] = None
        self._signatures: typing.Optional[AsyncSignaturesClient] = None

    @property
    def with_raw_response(self) -> AsyncRawPayrocCloudClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPayrocCloudClient
        """
        return self._raw_client

    @property
    def payment_instructions(self):
        if self._payment_instructions is None:
            from .payment_instructions.client import AsyncPaymentInstructionsClient  # noqa: E402

            self._payment_instructions = AsyncPaymentInstructionsClient(client_wrapper=self._client_wrapper)
        return self._payment_instructions

    @property
    def refund_instructions(self):
        if self._refund_instructions is None:
            from .refund_instructions.client import AsyncRefundInstructionsClient  # noqa: E402

            self._refund_instructions = AsyncRefundInstructionsClient(client_wrapper=self._client_wrapper)
        return self._refund_instructions

    @property
    def signature_instructions(self):
        if self._signature_instructions is None:
            from .signature_instructions.client import AsyncSignatureInstructionsClient  # noqa: E402

            self._signature_instructions = AsyncSignatureInstructionsClient(client_wrapper=self._client_wrapper)
        return self._signature_instructions

    @property
    def signatures(self):
        if self._signatures is None:
            from .signatures.client import AsyncSignaturesClient  # noqa: E402

            self._signatures = AsyncSignaturesClient(client_wrapper=self._client_wrapper)
        return self._signatures
