# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....core.serialization import FieldMetadata
from ....types.ach_payload_account_type import AchPayloadAccountType
from ....types.ach_payload_sec_code import AchPayloadSecCode
from ....types.card_payload_account_type import CardPayloadAccountType
from ....types.card_payload_card_details import CardPayloadCardDetails
from ....types.pad_payload_account_type import PadPayloadAccountType


class SingleUseTokenRequestSource_Ach(UniversalBaseModel):
    """
    Object that contains information about the payment method to tokenize.
    """

    type: typing.Literal["ach"] = "ach"
    account_type: typing_extensions.Annotated[
        typing.Optional[AchPayloadAccountType], FieldMetadata(alias="accountType")
    ] = None
    sec_code: typing_extensions.Annotated[typing.Optional[AchPayloadSecCode], FieldMetadata(alias="secCode")] = None
    name_on_account: typing_extensions.Annotated[str, FieldMetadata(alias="nameOnAccount")]
    account_number: typing_extensions.Annotated[str, FieldMetadata(alias="accountNumber")]
    routing_number: typing_extensions.Annotated[str, FieldMetadata(alias="routingNumber")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SingleUseTokenRequestSource_Pad(UniversalBaseModel):
    """
    Object that contains information about the payment method to tokenize.
    """

    type: typing.Literal["pad"] = "pad"
    account_type: typing_extensions.Annotated[
        typing.Optional[PadPayloadAccountType], FieldMetadata(alias="accountType")
    ] = None
    name_on_account: typing_extensions.Annotated[str, FieldMetadata(alias="nameOnAccount")]
    account_number: typing_extensions.Annotated[str, FieldMetadata(alias="accountNumber")]
    transit_number: typing_extensions.Annotated[str, FieldMetadata(alias="transitNumber")]
    institution_number: typing_extensions.Annotated[str, FieldMetadata(alias="institutionNumber")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class SingleUseTokenRequestSource_Card(UniversalBaseModel):
    """
    Object that contains information about the payment method to tokenize.
    """

    type: typing.Literal["card"] = "card"
    account_type: typing_extensions.Annotated[
        typing.Optional[CardPayloadAccountType], FieldMetadata(alias="accountType")
    ] = None
    card_details: typing_extensions.Annotated[CardPayloadCardDetails, FieldMetadata(alias="cardDetails")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


SingleUseTokenRequestSource = typing_extensions.Annotated[
    typing.Union[SingleUseTokenRequestSource_Ach, SingleUseTokenRequestSource_Pad, SingleUseTokenRequestSource_Card],
    pydantic.Field(discriminator="type"),
]
