# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....types.merchant_balance import MerchantBalance
from ....types.paginated_list import PaginatedList


class RetrieveBalanceFundingActivityResponse(PaginatedList):
    data: typing.List[MerchantBalance] = pydantic.Field()
    """
    Array of merchantBalance objects.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
