# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class PayrocEnvironment:
    PRODUCTION: PayrocEnvironment
    UAT: PayrocEnvironment

    def __init__(self, *, api: str, identity: str):
        self.api = api
        self.identity = identity


PayrocEnvironment.PRODUCTION = PayrocEnvironment(
    api="https://api.payroc.com/v1", identity="https://identity.payroc.com"
)
PayrocEnvironment.UAT = PayrocEnvironment(
    api="https://api.uat.payroc.com/v1", identity="https://identity.uat.payroc.com"
)
