# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from . import secure_tokens, single_use_tokens
    from .secure_tokens import (
        TokenizationRequestMitAgreement,
        TokenizationRequestSource,
        TokenizationRequestSource_Ach,
        TokenizationRequestSource_Card,
        TokenizationRequestSource_Pad,
        TokenizationRequestSource_SingleUseToken,
        TokenizationRequestThreeDSecure,
        TokenizationRequestThreeDSecure_GatewayThreeDSecure,
        TokenizationRequestThreeDSecure_ThirdPartyThreeDSecure,
    )
    from .single_use_tokens import (
        SingleUseTokenRequestChannel,
        SingleUseTokenRequestSource,
        SingleUseTokenRequestSource_Ach,
        SingleUseTokenRequestSource_Card,
        SingleUseTokenRequestSource_Pad,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "SingleUseTokenRequestChannel": ".single_use_tokens",
    "SingleUseTokenRequestSource": ".single_use_tokens",
    "SingleUseTokenRequestSource_Ach": ".single_use_tokens",
    "SingleUseTokenRequestSource_Card": ".single_use_tokens",
    "SingleUseTokenRequestSource_Pad": ".single_use_tokens",
    "TokenizationRequestMitAgreement": ".secure_tokens",
    "TokenizationRequestSource": ".secure_tokens",
    "TokenizationRequestSource_Ach": ".secure_tokens",
    "TokenizationRequestSource_Card": ".secure_tokens",
    "TokenizationRequestSource_Pad": ".secure_tokens",
    "TokenizationRequestSource_SingleUseToken": ".secure_tokens",
    "TokenizationRequestThreeDSecure": ".secure_tokens",
    "TokenizationRequestThreeDSecure_GatewayThreeDSecure": ".secure_tokens",
    "TokenizationRequestThreeDSecure_ThirdPartyThreeDSecure": ".secure_tokens",
    "secure_tokens": ".secure_tokens",
    "single_use_tokens": ".single_use_tokens",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "SingleUseTokenRequestChannel",
    "SingleUseTokenRequestSource",
    "SingleUseTokenRequestSource_Ach",
    "SingleUseTokenRequestSource_Card",
    "SingleUseTokenRequestSource_Pad",
    "TokenizationRequestMitAgreement",
    "TokenizationRequestSource",
    "TokenizationRequestSource_Ach",
    "TokenizationRequestSource_Card",
    "TokenizationRequestSource_Pad",
    "TokenizationRequestSource_SingleUseToken",
    "TokenizationRequestThreeDSecure",
    "TokenizationRequestThreeDSecure_GatewayThreeDSecure",
    "TokenizationRequestThreeDSecure_ThirdPartyThreeDSecure",
    "secure_tokens",
    "single_use_tokens",
]
